using System.Collections.Generic;

namespace DogtorBurguer
{
    /// <summary>FR strings — one entry per LocKey (Loc's editor boot check screams on gaps).
    /// Machine-drafted 2026-09-08, native-phrasing polish pass the same day.</summary>
    public static class Strings_FR
    {
        public static readonly Dictionary<LocKey, string> Table = new()
        {
            { LocKey.SettingsTitle, "RÉGLAGES" },
            { LocKey.SettingsSoundOn, "Son: ON" },
            { LocKey.SettingsSoundOff, "Son: OFF" },
            { LocKey.SettingsMusicOn, "Musique: ON" },
            { LocKey.SettingsMusicOff, "Musique: OFF" },
            { LocKey.SettingsControlsDrag, "Contrôles: Glisser" },
            { LocKey.SettingsControlsTap, "Contrôles: Toucher" },
            { LocKey.SettingsStartLevel, "DÉBUT: NIVEAU {0}" },
            { LocKey.SettingsQuit, "Retour au Menu" },
            { LocKey.SettingsLanguage, "Langue: {0}" },
            { LocKey.SettingsRestart, "Recommencer" },
            { LocKey.MenuPlay, "JOUER" },
            { LocKey.MenuResume, "REPRENDRE" },
            { LocKey.MenuCredits, "CRÉDITS" },
            { LocKey.MenuShop, "BOUTIQUE" },
            { LocKey.MenuSupportDevs, "Soutiens les devs!" },
            { LocKey.GameOverTitle, "GAME OVER..." },
            { LocKey.GameOverStarsEarned, "Tu as gagné {0} étoiles!" },
            { LocKey.GameOverContinue, "Continuer" },
            { LocKey.GameOverNoMoreContinues, "Plus de continues" },
            { LocKey.GameOverWatch, "Regarder" },
            { LocKey.GameOverLoading, "Chargement..." },
            { LocKey.GameOverMainMenu, "Menu\nPrincipal" },
            { LocKey.GameOverRetry, "Réessayer" },
            { LocKey.HowToTitle, "COMMENT JOUER" },
            { LocKey.HowToPlayTutorial, "LANCER LE TUTO" },
            { LocKey.HowToControls, "CONTRÔLES" },
            { LocKey.HowToControls1, "Glisse, ou touche à gauche ou à droite du chef, pour le déplacer." },
            { LocKey.HowToControls2, "Touche le chef pour échanger les deux colonnes devant lui." },
            { LocKey.HowToControls3, "Touche un ingrédient qui tombe pour l'accélérer." },
            { LocKey.HowToControls4, "Touche un ingrédient en haut pour le faire tomber tout de suite." },
            { LocKey.HowToMatching, "PAIRES" },
            { LocKey.HowToMatching1, "Deux ingrédients identiques empilés éclatent et rapportent des points." },
            { LocKey.HowToMatching2, "Garde les colonnes basses: si une déborde, c'est fini!" },
            { LocKey.HowToBurgers, "BURGERS" },
            { LocKey.HowToBurgers1, "Ouvre avec un pain du bas." },
            { LocKey.HowToBurgers2, "Empile des ingrédients dessus." },
            { LocKey.HowToBurgers3, "Ferme avec un pain du haut pour servir le burger." },
            { LocKey.HowToBurgers4, "Les gros burgers rapportent plus!" },
            { LocKey.HowToOrders, "COMMANDES SPÉCIALES" },
            { LocKey.HowToOrders1, "Sers un burger qui correspond à la commande affichée." },
            { LocKey.HowToOrders2, "Les commandes rapportent des étoiles et font monter ton multiplicateur." },
            { LocKey.PowerUps, "POWER-UPS" },
            { LocKey.HowToPowerUpsA1, "La Fée Burger apporte gemmes, étoiles et power-ups. Touche-la avant qu'elle parte!" },
            { LocKey.HowToPowerUpsA2, "Fais glisser un power-up de son emplacement vers une colonne pour l'utiliser." },
            { LocKey.HowToPowerUpsB1, "Le ketchup vide sa colonne." },
            { LocKey.HowToPowerUpsB2, "La moutarde prend les deux types du haut de sa colonne et les balaie de tout le plateau." },
            { LocKey.HowToPowerUpsB3, "La brochette pousse un pain du bas jusqu'à la base de sa colonne." },
            { LocKey.CreditsTitle, "CRÉDITS" },
            { LocKey.CreditsGameBy, "UN JEU DE" },
            { LocKey.CreditsArtBy, "GRAPHISMES DE" },
            { LocKey.CreditsMusicBy, "MUSIQUE DE" },
            { LocKey.SpecialOrder, "COMMANDE SPÉCIALE" },
            { LocKey.MultTab, "MULT" },
            { LocKey.TooBad, "Dommage!" },
            { LocKey.OrderComplete, "Commande servie!" },
            { LocKey.NamerGood, "Bien!" },
            { LocKey.NamerTasty, "Savoureux!" },
            { LocKey.NamerGreat, "Génial!" },
            { LocKey.NamerDelicious, "Délicieux!" },
            { LocKey.NamerAwesome, "Énorme!!" },
            { LocKey.NamerIncredible, "Incroyable!!" },
            { LocKey.NamerExquisite, "Exquis!!" },
            { LocKey.NamerGourmet, "Gourmet!!" },
            { LocKey.NamerJustBread, "Que du pain..." },
            { LocKey.NamerDogtorBurger, "DOGTOR BURGER!!!" },
            { LocKey.TutMoveTitle, "BOUGE!" },
            { LocKey.TutMoveTap, "Touche à GAUCHE ou à DROITE du Dogtor pour le déplacer." },
            { LocKey.TutMoveSwipe, "Glisse à gauche ou à droite pour déplacer le Dogtor." },
            { LocKey.TutSwapTitle, "ÉCHANGE!" },
            { LocKey.TutSwapBody, "Touche le Dogtor pour échanger les colonnes devant lui!" },
            { LocKey.TutMatchTitle, "PAIRE!" },
            { LocKey.TutMatchBody, "Deux identiques éclatent! Échange pour viser sa jumelle.\nPaires: {0}/{1}" },
            { LocKey.TutMatchDone, "Délicieux! Les paires nettoient le comptoir et rapportent." },
            { LocKey.TutFastDropTitle, "PRESSÉ?" },
            { LocKey.TutFastDropBody, "Touche un ingrédient qui tombe pour le faire descendre vite!" },
            { LocKey.TutFastDropDone, "Zou! Précipite une pièce quand tu la veux en bas." },
            { LocKey.TutBurgerTitle, "BURGER TIME!" },
            { LocKey.TutBurgerBody, "ÉCHANGE pour tout poser sur le pain du bas! Referme avec le haut." },
            { LocKey.TutBurgerDone, "Servi! Les gros burgers rapportent bien plus." },
            { LocKey.TutOrderTitle, "COMMANDE SPÉCIALE!" },
            { LocKey.TutOrderBody, "Un client veut CELUI-CI! L'ordre importe peu - construis-le." },
            { LocKey.TutOrderDone, "Les commandes montent ton multiplicateur sur CHAQUE point!" },
            { LocKey.TutPowerUpTitle, "POWER-UP!" },
            { LocKey.TutKetchupBody, "Ketchup gratuit! Fais-le glisser sur la colonne encombrée." },
            { LocKey.TutKetchupDone, "Impeccable! Le ketchup vide une colonne entière." },
            { LocKey.TutMustardBody, "Moutarde gratuite! Vise une colonne: ses deux ingrédients du haut disparaissent partout!" },
            { LocKey.TutMustardDone, "Grand ménage! La moutarde paie si un ingrédient est partout." },
            { LocKey.TutSkewerBody, "Brochette gratuite! Lâche-la sur la colonne au pain enfoui." },
            { LocKey.TutSkewerDone, "Sauvé et servi! Un pain enfoui, c'est un burger qui attend." },
            { LocKey.TutReadyTitle, "PRÊT!" },
            { LocKey.TutReadyBody, "Touche les Fées Burger pour plus de power-ups! Le resto est à toi." },
            { LocKey.TutTapToContinue, "TOUCHE POUR CONTINUER" },
            { LocKey.TutSkip, "PASSER" },
            { LocKey.ShopTitle, "BOUTIQUE" },
            { LocKey.ShopDogtorSkins, "SKINS DOGTOR" },
            { LocKey.ShopIngredientSkins, "SKINS INGRÉDIENTS" },
            { LocKey.ShopProCookPack, "PACK PRO DU CHEF" },
            { LocKey.ShopStars, "ÉTOILES" },
            { LocKey.ShopGems, "GEMMES" },
            { LocKey.ShopRemoveAds, "SUPPRIMER LES PUBS" },
            { LocKey.ShopRewardAds, "LES PUBS BONUS RESTENT" },
            { LocKey.ShopOneTimeBuy, "ACHAT\nUNIQUE" },
            { LocKey.ShopThankYou, "MERCI DE NOUS\nSOUTENIR!" },
            { LocKey.ShopWatchAd, "VOIR LA PUB" },
            { LocKey.ShopTomorrow, "DEMAIN!" },
            { LocKey.ShopLoading, "CHARGEMENT..." },
            { LocKey.ShopRestorePurchases, "Restaurer les achats" },
            { LocKey.ShopBuyAmount, "Acheter {0}" },
            { LocKey.ShopForCost, "pour {0}" },
            { LocKey.ShopBuy, "ACHETER" },
            { LocKey.ShopCancel, "ANNULER" },
            { LocKey.ShopEquipped, "ÉQUIPÉ" },
            { LocKey.ShopEquip, "ÉQUIPER" },
            { LocKey.StatLevel, "Niveau" },
            { LocKey.StatScore, "Score" },
            { LocKey.SkinChefDefault, "Chef classique" },
            { LocKey.SkinChefBurgerchain, "Chef fast-food" },
            { LocKey.SkinChefEuropean, "Chef européen" },
            { LocKey.SkinChefJapanese, "Chef japonais" },
            { LocKey.SkinChefMexican, "Chef mexicain" },
            { LocKey.SkinChefRoyale, "Chef Royale" },
            { LocKey.SkinBunDefault, "Pain classique" },
            { LocKey.SkinBunGourmet, "Pain complet" },
            { LocKey.SkinBunGold, "Pain en or" },
            { LocKey.SkinBunRustic, "Pain rustique" },
            { LocKey.SkinBunBlack, "Pain noir" },
            { LocKey.SkinMeatDefault, "Steak classique" },
            { LocKey.SkinMeatGourmet, "Burger poulet" },
            { LocKey.SkinMeatGold, "Steak en or" },
            { LocKey.SkinMeatVegan, "Burger vegan" },
            { LocKey.SkinMeatWagyu, "Steak wagyu" },
            { LocKey.SkinCheeseDefault, "Fromage classique" },
            { LocKey.SkinCheeseGourmet, "Cheddar" },
            { LocKey.SkinCheeseGold, "Fromage en or" },
            { LocKey.SkinCheeseShredded, "Fromage râpé" },
            { LocKey.SkinCheeseBlue, "Fromage bleu" },
            { LocKey.SkinTomatoDefault, "Tomate classique" },
            { LocKey.SkinTomatoGourmet, "Tomate cerise" },
            { LocKey.SkinTomatoGold, "Tomate en or" },
            { LocKey.SkinTomatoPico, "Pico de gallo" },
            { LocKey.SkinTomatoKumato, "Kumato" },
            { LocKey.SkinBaconDefault, "Bacon" },
            { LocKey.SkinBaconGourmet, "Lardons" },
            { LocKey.SkinBaconGold, "Bacon en or" },
            { LocKey.SkinBaconPulledpork, "Porc effiloché" },
            { LocKey.SkinBaconIberic, "Jambon ibérique" },
            { LocKey.SkinOnionDefault, "Oignon classique" },
            { LocKey.SkinOnionGourmet, "Oignon caramélisé" },
            { LocKey.SkinOnionGold, "Oignon en or" },
            { LocKey.SkinOnionPickled, "Oignon mariné" },
            { LocKey.SkinOnionCrispy, "Oignon frit" },
            { LocKey.SkinPickleDefault, "Cornichon classique" },
            { LocKey.SkinPickleGourmet, "Relish cornichon" },
            { LocKey.SkinPickleGold, "Cornichon en or" },
            { LocKey.SkinPickleBellpepper, "Poivron" },
            { LocKey.SkinPickleJalapeno, "Jalapeño" },
            { LocKey.SkinLettuceDefault, "Salade classique" },
            { LocKey.SkinLettuceGourmet, "Salade émincée" },
            { LocKey.SkinLettuceGold, "Salade en or" },
            { LocKey.SkinLettuceAvocado, "Avocat" },
            { LocKey.SkinLettucePurple, "Chou rouge" },
            { LocKey.SkinEggDefault, "Œuf classique" },
            { LocKey.SkinEggBoiled, "Œuf dur" },
            { LocKey.SkinEggGold, "Œuf en or" },
            { LocKey.SkinEggGourmet, "Œuf de caille" },
            { LocKey.SkinEggOmelet, "Omelette" },
        };
    }
}
