using System.Collections.Generic;

namespace DogtorBurguer
{
    /// <summary>PT strings — one entry per LocKey (Loc's editor boot check screams on gaps).
    /// Machine-drafted 2026-09-08, native-phrasing polish pass the same day.</summary>
    public static class Strings_PT
    {
        public static readonly Dictionary<LocKey, string> Table = new()
        {
            { LocKey.SettingsTitle, "AJUSTES" },
            { LocKey.SettingsSoundOn, "Som: LIGADO" },
            { LocKey.SettingsSoundOff, "Som: DESLIGADO" },
            { LocKey.SettingsControlsDrag, "Controles: Arrastar" },
            { LocKey.SettingsControlsTap, "Controles: Tocar" },
            { LocKey.SettingsStartLevel, "INÍCIO: NÍVEL {0}" },
            { LocKey.SettingsQuit, "Voltar ao Menu" },
            { LocKey.SettingsLanguage, "Idioma: {0}" },
            { LocKey.SettingsRestart, "Reiniciar" },
            { LocKey.MenuPlay, "JOGAR" },
            { LocKey.MenuCredits, "CRÉDITOS" },
            { LocKey.MenuShop, "LOJA" },
            { LocKey.MenuSupportDevs, "Apoie os devs!" },
            { LocKey.GameOverTitle, "GAME OVER..." },
            { LocKey.GameOverStarsEarned, "Você ganhou {0} estrelas!" },
            { LocKey.GameOverContinue, "Continuar" },
            { LocKey.GameOverNoMoreContinues, "Não dá mais para continuar" },
            { LocKey.GameOverWatch, "Assistir" },
            { LocKey.GameOverLoading, "Carregando..." },
            { LocKey.GameOverMainMenu, "Menu\nPrincipal" },
            { LocKey.GameOverRetry, "De novo" },
            { LocKey.HowToTitle, "COMO JOGAR" },
            { LocKey.HowToPlayTutorial, "JOGAR TUTORIAL" },
            { LocKey.HowToControls, "CONTROLES" },
            { LocKey.HowToControls1, "- Deslize para a esquerda ou direita para mover o chef." },
            { LocKey.HowToControls2, "- Toque no chef para trocar as duas colunas na frente dele." },
            { LocKey.HowToControls3, "- Toque num ingrediente caindo para ele cair mais rápido." },
            { LocKey.HowToControls4, "- Toque numa seta lá de cima para soltar o ingrediente na hora." },
            { LocKey.HowToMatching, "PARES" },
            { LocKey.HowToMatching1, "- Dois ingredientes iguais empilhados estouram e dão pontos." },
            { LocKey.HowToMatching2, "- Mantenha as colunas baixas: se uma transbordar, acabou!" },
            { LocKey.HowToBurgers, "HAMBÚRGUERES" },
            { LocKey.HowToBurgers1, "- Abra com um pão de baixo." },
            { LocKey.HowToBurgers2, "- Empilhe ingredientes em cima." },
            { LocKey.HowToBurgers3, "- Feche com um pão de cima para servir o hambúrguer." },
            { LocKey.HowToBurgers4, "- Hambúrgueres maiores dão mais pontos!" },
            { LocKey.HowToOrders, "PEDIDOS ESPECIAIS" },
            { LocKey.HowToOrders1, "- Sirva um hambúrguer que corresponda ao pedido mostrado." },
            { LocKey.HowToOrders2, "- Pedidos pagam estrelas e aumentam seu multiplicador." },
            { LocKey.PowerUps, "POWER-UPS" },
            { LocKey.HowToPowerUpsA1, "- A Fada Burger traz gemas, estrelas e power-ups. Toque nela antes que vá embora!" },
            { LocKey.HowToPowerUpsA2, "- Arraste um power-up do slot até uma coluna para usar." },
            { LocKey.HowToPowerUpsB1, "- O ketchup limpa a coluna inteira." },
            { LocKey.HowToPowerUpsB2, "- A mostarda pega os dois ingredientes do topo da coluna e varre os dois do tabuleiro inteiro." },
            { LocKey.HowToPowerUpsB3, "- O espeto empurra um pão de baixo até a base da coluna." },
            { LocKey.CreditsTitle, "CRÉDITOS" },
            { LocKey.CreditsGameBy, "UM JOGO DE" },
            { LocKey.CreditsArtBy, "ARTE DE" },
            { LocKey.CreditsMusicBy, "MÚSICA DE" },
            { LocKey.SpecialOrder, "PEDIDO ESPECIAL" },
            { LocKey.TooBad, "Que pena!" },
            { LocKey.OrderComplete, "Pedido completo!" },
            { LocKey.NamerGood, "Bom!" },
            { LocKey.NamerTasty, "Gostoso!" },
            { LocKey.NamerGreat, "Ótimo!" },
            { LocKey.NamerDelicious, "Delicioso!" },
            { LocKey.NamerAwesome, "Demais!!" },
            { LocKey.NamerIncredible, "Incrível!!" },
            { LocKey.NamerExquisite, "Requintado!!" },
            { LocKey.NamerGourmet, "Gourmet!!" },
            { LocKey.NamerJustBread, "Só pão..." },
            { LocKey.NamerDogtorBurger, "DOGTOR BURGER!!!" },
            { LocKey.TutMoveTitle, "MOVA-SE!" },
            { LocKey.TutMoveTap, "Toque à ESQUERDA ou à DIREITA do Dogtor para movê-lo entre os balcões." },
            { LocKey.TutMoveSwipe, "Deslize para a esquerda ou direita para mover o Dogtor entre os balcões." },
            { LocKey.TutSwapTitle, "TROQUE!" },
            { LocKey.TutSwapBody, "Toque no Dogtor para trocar as duas colunas na frente dele!" },
            { LocKey.TutMatchTitle, "PAR!" },
            { LocKey.TutMatchBody, "Dois iguais estouram! Troque as colunas para a carne cair em cima da outra igual." },
            { LocKey.TutMatchDone, "Delicioso! Formar pares limpa o balcão e dá pontos." },
            { LocKey.TutBurgerTitle, "HORA DO BURGER!" },
            { LocKey.TutBurgerBody, "Sua vez! Um pão de baixo abre o hambúrguer - TROQUE as colunas para cada peça cair EM CIMA dele. Feche com o pão de cima!" },
            { LocKey.TutBurgerDone, "Servido! Hambúrgueres maiores dão muito mais pontos." },
            { LocKey.TutOrderTitle, "PEDIDO ESPECIAL!" },
            { LocKey.TutOrderBody, "Um cliente quer ESTE hambúrguer exato! A ORDEM dos ingredientes não importa - monte e sirva!" },
            { LocKey.TutOrderDone, "Pedidos enchem o medidor e aumentam seu multiplicador - para CADA ponto que você fizer!" },
            { LocKey.TutPowerUpTitle, "POWER-UP!" },
            { LocKey.TutPowerUpBody, "Um ketchup grátis! Arraste do slot até a coluna bagunçada para limpar." },
            { LocKey.TutPowerUpDone, "Impecável! As Fadas Burger trazem mais power-ups - toque nelas quando passarem voando." },
            { LocKey.TutReadyTitle, "PRONTO!" },
            { LocKey.TutReadyBody, "O restaurante é seu. Sirva bem, Dogtor!" },
            { LocKey.TutTapToContinue, "TOQUE PARA CONTINUAR" },
            { LocKey.TutSkip, "PULAR" },
            { LocKey.ShopTitle, "LOJA" },
            { LocKey.ShopDogtorSkins, "SKINS DE DOGTOR" },
            { LocKey.ShopIngredientSkins, "SKINS DE INGREDIENTES" },
            { LocKey.ShopProCookPack, "PACOTE PRO DO CHEF" },
            { LocKey.ShopStars, "ESTRELAS" },
            { LocKey.ShopGems, "GEMAS" },
            { LocKey.ShopRemoveAds, "REMOVER ANÚNCIOS" },
            { LocKey.ShopRewardAds, "ANÚNCIOS DE RECOMPENSA CONTINUAM" },
            { LocKey.ShopOneTimeBuy, "COMPRA\nÚNICA" },
            { LocKey.ShopThankYou, "OBRIGADO POR\nNOS APOIAR!" },
            { LocKey.ShopWatchAd, "VER ANÚNCIO" },
            { LocKey.ShopTomorrow, "AMANHÃ!" },
            { LocKey.ShopLoading, "CARREGANDO..." },
            { LocKey.ShopRestorePurchases, "Restaurar compras" },
            { LocKey.ShopBuyAmount, "Comprar {0}" },
            { LocKey.ShopForCost, "por {0}" },
            { LocKey.ShopBuy, "COMPRAR" },
            { LocKey.ShopCancel, "CANCELAR" },
            { LocKey.ShopEquipped, "EQUIPADO" },
            { LocKey.ShopEquip, "EQUIPAR" },
            { LocKey.StatLevel, "Nível" },
            { LocKey.StatScore, "Pontos" },
        };
    }
}
