using System.Collections.Generic;

namespace DogtorBurguer
{
    /// <summary>TR strings — one entry per LocKey (Loc's editor boot check screams on gaps).
    /// Machine-drafted 2026-09-08, native-phrasing polish pass the same day.</summary>
    public static class Strings_TR
    {
        public static readonly Dictionary<LocKey, string> Table = new()
        {
            { LocKey.SettingsTitle, "AYARLAR" },
            { LocKey.SettingsSoundOn, "Ses: AÇIK" },
            { LocKey.SettingsSoundOff, "Ses: KAPALI" },
            { LocKey.SettingsMusicOn, "Müzik: AÇIK" },
            { LocKey.SettingsMusicOff, "Müzik: KAPALI" },
            { LocKey.SettingsControlsDrag, "Kontrol: Sürükle" },
            { LocKey.SettingsControlsTap, "Kontrol: Dokun" },
            { LocKey.SettingsStartLevel, "BAŞLA: SEVİYE {0}" },
            { LocKey.SettingsQuit, "Menüye Dön" },
            { LocKey.SettingsLanguage, "Dil: {0}" },
            { LocKey.SettingsRestart, "Yeniden Başlat" },
            { LocKey.MenuPlay, "OYNA" },
            { LocKey.MenuResume, "DEVAM ET" },
            { LocKey.MenuCredits, "KÜNYE" },
            { LocKey.MenuShop, "MAĞAZA" },
            { LocKey.MenuSupportDevs, "Geliştiricilere destek ol!" },
            { LocKey.GameOverTitle, "GAME OVER..." },
            { LocKey.GameOverStarsEarned, "{0} yıldız kazandın!" },
            { LocKey.GameOverContinue, "Devam" },
            { LocKey.GameOverNoMoreContinues, "Devam hakkın bitti" },
            { LocKey.GameOverWatch, "İzle" },
            { LocKey.GameOverLoading, "Yükleniyor..." },
            { LocKey.GameOverMainMenu, "Ana\nMenü" },
            { LocKey.GameOverRetry, "Tekrar Dene" },
            { LocKey.HowToTitle, "NASIL OYNANIR" },
            { LocKey.HowToPlayTutorial, "EĞİTİMİ OYNA" },
            { LocKey.HowToControls, "KONTROLLER" },
            { LocKey.HowToControls1, "- Şefi hareket ettirmek için kaydır ya da onun soluna veya sağına dokun." },
            { LocKey.HowToControls2, "- Önündeki iki sütunu takas etmek için şefe dokun." },
            { LocKey.HowToControls3, "- Düşen bir malzemeye dokunarak hızlandır." },
            { LocKey.HowToControls4, "- Yukarıdaki bir malzemeye dokunarak hemen düşür." },
            { LocKey.HowToMatching, "EŞLEŞTİRME" },
            { LocKey.HowToMatching1, "- Üst üste gelen iki aynı malzeme patlar ve puan verir." },
            { LocKey.HowToMatching2, "- Sütunları alçak tut: biri taşarsa oyun biter!" },
            { LocKey.HowToBurgers, "BURGERLER" },
            { LocKey.HowToBurgers1, "- Alt ekmekle başla." },
            { LocKey.HowToBurgers2, "- Üzerine malzeme yığ." },
            { LocKey.HowToBurgers3, "- Üst ekmekle kapatıp burgeri servis et." },
            { LocKey.HowToBurgers4, "- Büyük burgerler daha çok puan verir!" },
            { LocKey.HowToOrders, "ÖZEL SİPARİŞLER" },
            { LocKey.HowToOrders1, "- Gösterilen siparişe uyan bir burger servis et." },
            { LocKey.HowToOrders2, "- Siparişler yıldız kazandırır ve çarpanını yükseltir." },
            { LocKey.PowerUps, "GÜÇLENDİRMELER" },
            { LocKey.HowToPowerUpsA1, "- Burger Perisi mücevher, yıldız ve güçlendirme getirir. Gitmeden ona dokun!" },
            { LocKey.HowToPowerUpsA2, "- Kullanmak için güçlendirmeyi yuvasından bir sütuna sürükle." },
            { LocKey.HowToPowerUpsB1, "- Ketçap kendi sütununu temizler." },
            { LocKey.HowToPowerUpsB2, "- Hardal, sütunun en üstündeki iki malzeme türünü tüm tahtadan süpürür." },
            { LocKey.HowToPowerUpsB3, "- Şiş, alt ekmeği sütunun dibine iter." },
            { LocKey.CreditsTitle, "KÜNYE" },
            { LocKey.CreditsGameBy, "OYUNU YAPAN" },
            { LocKey.CreditsArtBy, "ÇİZİMLER" },
            { LocKey.CreditsMusicBy, "MÜZİKLER" },
            { LocKey.SpecialOrder, "ÖZEL SİPARİŞ" },
            { LocKey.TooBad, "Tüh!" },
            { LocKey.OrderComplete, "Sipariş tamam!" },
            { LocKey.NamerGood, "İyi!" },
            { LocKey.NamerTasty, "Lezzetli!" },
            { LocKey.NamerGreat, "Harika!" },
            { LocKey.NamerDelicious, "Nefis!" },
            { LocKey.NamerAwesome, "Müthiş!!" },
            { LocKey.NamerIncredible, "İnanılmaz!!" },
            { LocKey.NamerExquisite, "Enfes!!" },
            { LocKey.NamerGourmet, "Gurme!!" },
            { LocKey.NamerJustBread, "Sadece ekmek..." },
            { LocKey.NamerDogtorBurger, "DOGTOR BURGER!!!" },
            { LocKey.TutMoveTitle, "HAREKET!" },
            { LocKey.TutMoveTap, "Dogtor'u hareket ettirmek için SOLUNA veya SAĞINA dokun." },
            { LocKey.TutMoveSwipe, "Dogtor'u hareket ettirmek için sola veya sağa kaydır." },
            { LocKey.TutSwapTitle, "TAKAS!" },
            { LocKey.TutSwapBody, "Önündeki yığınları takas etmek için Dogtor'a dokun!" },
            { LocKey.TutMatchTitle, "EŞLEŞME!" },
            { LocKey.TutMatchBody, "İki aynı patlar! Eşinin üstüne insin diye takas et.\nÇiftler: {0}/{1}" },
            { LocKey.TutMatchDone, "Nefis! Çiftler tezgahı temizler ve puan kazandırır." },
            { LocKey.TutFastDropTitle, "ACELEN Mİ VAR?" },
            { LocKey.TutFastDropBody, "Düşen bir malzemeye dokun, hızla aşağı insin!" },
            { LocKey.TutFastDropDone, "Vınn! Bir parçayı istediğin an hızla indir." },
            { LocKey.TutBurgerTitle, "BURGER ZAMANI!" },
            { LocKey.TutBurgerBody, "Her şey alt ekmeğe insin diye TAKAS ET! Üstünü kapat." },
            { LocKey.TutBurgerDone, "Servis edildi! Büyük burgerler çok daha fazla puan verir." },
            { LocKey.TutOrderTitle, "ÖZEL SİPARİŞ!" },
            { LocKey.TutOrderBody, "Müşteri BUNU istiyor! Sıra önemli değil, sadece yap." },
            { LocKey.TutOrderDone, "Siparişler HER puanda çarpanını yükseltir!" },
            { LocKey.TutPowerUpTitle, "GÜÇLENDİRME!" },
            { LocKey.TutKetchupBody, "Bedava ketçap! Dağınık sütuna sürükle." },
            { LocKey.TutKetchupDone, "Pırıl pırıl! Ketçap koca bir sütunu boşaltır." },
            { LocKey.TutMustardBody, "Bedava hardal! En üstteki İKİ malzemeyi tüm tezgahtan siler." },
            { LocKey.TutMustardDone, "Tam süpürme! Bir malzeme her yerdeyse hardal çok iş görür." },
            { LocKey.TutSkewerBody, "Bedava şiş! Ekmeğin gömülü olduğu sütuna bırak." },
            { LocKey.TutSkewerDone, "Kurtarıldı! Ekmek yine en altta, doldurmaya hazır." },
            { LocKey.TutReadyTitle, "HAZIR!" },
            { LocKey.TutReadyBody, "Daha çok güçlendirme için Burger Perilerine dokun! Burası senin." },
            { LocKey.TutTapToContinue, "DEVAM İÇİN DOKUN" },
            { LocKey.TutSkip, "GEÇ" },
            { LocKey.ShopTitle, "MAĞAZA" },
            { LocKey.ShopDogtorSkins, "DOGTOR KOSTÜMLERİ" },
            { LocKey.ShopIngredientSkins, "MALZEME KOSTÜMLERİ" },
            { LocKey.ShopProCookPack, "PRO ŞEF PAKETİ" },
            { LocKey.ShopStars, "YILDIZLAR" },
            { LocKey.ShopGems, "MÜCEVHERLER" },
            { LocKey.ShopRemoveAds, "REKLAMLARI KALDIR" },
            { LocKey.ShopRewardAds, "ÖDÜLLÜ REKLAMLAR KAYBOLMAZ" },
            { LocKey.ShopOneTimeBuy, "TEK\nSEFERLİK" },
            { LocKey.ShopThankYou, "DESTEĞİN İÇİN\nTEŞEKKÜRLER!" },
            { LocKey.ShopWatchAd, "REKLAM İZLE" },
            { LocKey.ShopTomorrow, "YARIN!" },
            { LocKey.ShopLoading, "YÜKLENİYOR..." },
            { LocKey.ShopRestorePurchases, "Satın alımları geri yükle" },
            { LocKey.ShopBuyAmount, "{0} satın al" },
            { LocKey.ShopForCost, "fiyatı: {0}" },
            { LocKey.ShopBuy, "AL" },
            { LocKey.ShopCancel, "İPTAL" },
            { LocKey.ShopEquipped, "TAKILI" },
            { LocKey.ShopEquip, "TAK" },
            { LocKey.StatLevel, "Seviye" },
            { LocKey.StatScore, "Puan" },
        };
    }
}
