using System.Collections.Generic;

namespace DogtorBurguer
{
    /// <summary>EN strings — one entry per LocKey (Loc's editor boot check screams on gaps).
    /// Machine-drafted 2026-09-08, native-phrasing polish pass the same day.</summary>
    public static class Strings_EN
    {
        public static readonly Dictionary<LocKey, string> Table = new()
        {
            { LocKey.SettingsTitle, "SETTINGS" },
            { LocKey.SettingsSoundOn, "Sound: ON" },
            { LocKey.SettingsSoundOff, "Sound: OFF" },
            { LocKey.SettingsMusicOn, "Music: ON" },
            { LocKey.SettingsMusicOff, "Music: OFF" },
            { LocKey.SettingsControlsDrag, "Controls: Drag" },
            { LocKey.SettingsControlsTap, "Controls: Tap" },
            { LocKey.SettingsStartLevel, "START: LVL {0}" },
            { LocKey.SettingsQuit, "Quit to Menu" },
            { LocKey.SettingsLanguage, "Language: {0}" },
            { LocKey.SettingsRestart, "Restart" },
            { LocKey.MenuPlay, "PLAY" },
            { LocKey.MenuResume, "RESUME" },
            { LocKey.MenuCredits, "CREDITS" },
            { LocKey.MenuShop, "SHOP" },
            { LocKey.MenuSupportDevs, "Support the devs!" },
            { LocKey.GameOverTitle, "GAME OVER..." },
            { LocKey.GameOverStarsEarned, "{0} stars earned!" },
            { LocKey.GameOverContinue, "Continue" },
            { LocKey.GameOverNoMoreContinues, "No more continues" },
            { LocKey.GameOverWatch, "Watch" },
            { LocKey.GameOverLoading, "Loading..." },
            { LocKey.GameOverMainMenu, "Main\nMenu" },
            { LocKey.GameOverRetry, "Retry" },
            { LocKey.HowToTitle, "HOW TO PLAY" },
            { LocKey.HowToPlayTutorial, "PLAY TUTORIAL" },
            { LocKey.HowToControls, "CONTROLS" },
            { LocKey.HowToControls1, "Swipe, or tap to the chef's left or right, to move him." },
            { LocKey.HowToControls2, "Tap the chef to swap the two stacks in front of him." },
            { LocKey.HowToControls3, "Tap a falling ingredient to drop it faster." },
            { LocKey.HowToControls4, "Tap an upcoming ingredient at the top to drop it right away." },
            { LocKey.HowToMatching, "MATCHING" },
            { LocKey.HowToMatching1, "Two stacked ingredients of the same type pop and score points." },
            { LocKey.HowToMatching2, "Keep the columns low: if one overflows, the run ends!" },
            { LocKey.HowToBurgers, "BURGERS" },
            { LocKey.HowToBurgers1, "Open with a bottom bun." },
            { LocKey.HowToBurgers2, "Stack any ingredients on top." },
            { LocKey.HowToBurgers3, "Close with a top bun to serve the burger." },
            { LocKey.HowToBurgers4, "Bigger burgers score more!" },
            { LocKey.HowToOrders, "SPECIAL ORDERS" },
            { LocKey.HowToOrders1, "Serve a burger that fits the shown order." },
            { LocKey.HowToOrders2, "Orders pay stars and raise your multiplier." },
            { LocKey.PowerUps, "POWER-UPS" },
            { LocKey.HowToPowerUpsA1, "The Burger Fairy brings gems, stars and power-ups. Tap her before she leaves!" },
            { LocKey.HowToPowerUpsA2, "Drag a power-up from its slot onto a column to use it." },
            { LocKey.HowToPowerUpsB1, "Ketchup clears its column." },
            { LocKey.HowToPowerUpsB2, "Mustard sweeps the top two ingredient types of its column from the whole board." },
            { LocKey.HowToPowerUpsB3, "Skewer pushes a bottom bun down to the base of its column." },
            { LocKey.CreditsTitle, "CREDITS" },
            { LocKey.CreditsGameBy, "A GAME BY" },
            { LocKey.CreditsArtBy, "ART BY" },
            { LocKey.CreditsMusicBy, "MUSIC BY" },
            { LocKey.SpecialOrder, "SPECIAL ORDER" },
            { LocKey.MultTab, "MULT" },
            { LocKey.TooBad, "Too bad!" },
            { LocKey.OrderComplete, "Order Complete!" },
            { LocKey.NamerGood, "Good!" },
            { LocKey.NamerTasty, "Tasty!" },
            { LocKey.NamerGreat, "Great!" },
            { LocKey.NamerDelicious, "Delicious!" },
            { LocKey.NamerAwesome, "Awesome!!" },
            { LocKey.NamerIncredible, "Incredible!!" },
            { LocKey.NamerExquisite, "Exquisite!!" },
            { LocKey.NamerGourmet, "Gourmet!!" },
            { LocKey.NamerJustBread, "Just Bread..." },
            { LocKey.NamerDogtorBurger, "DOGTOR BURGER!!!" },
            { LocKey.TutMoveTitle, "MOVE!" },
            { LocKey.TutMoveTap, "Tap LEFT or RIGHT of the Dogtor to move him." },
            { LocKey.TutMoveSwipe, "Swipe left or right to move the Dogtor." },
            { LocKey.TutSwapTitle, "SWAP!" },
            { LocKey.TutSwapBody, "Tap the Dogtor to swap the stacks in front of him!" },
            { LocKey.TutMatchTitle, "MATCH!" },
            { LocKey.TutMatchBody, "Two of a kind pop! Swap so the piece lands on its twin.\nPairs: {0}/{1}" },
            { LocKey.TutMatchDone, "Delicious! Pairs clear the counter and score points." },
            { LocKey.TutFastDropTitle, "IN A HURRY?" },
            { LocKey.TutFastDropBody, "Tap a falling ingredient to drop it fast!" },
            { LocKey.TutFastDropDone, "Zoom! Rush a piece down whenever you need it." },
            { LocKey.TutBurgerTitle, "BURGER TIME!" },
            { LocKey.TutBurgerBody, "SWAP to land every piece on the bottom bun. Close it with the top bun!" },
            { LocKey.TutBurgerDone, "Served! Bigger burgers score much more." },
            { LocKey.TutOrderTitle, "SPECIAL ORDER!" },
            { LocKey.TutOrderBody, "A customer wants THIS burger! Any stacking order works - build it!" },
            { LocKey.TutOrderDone, "Orders raise your multiplier - on EVERY point you score!" },
            { LocKey.TutPowerUpTitle, "POWER-UP!" },
            { LocKey.TutKetchupBody, "Free Ketchup! Drag it from its slot onto the messy column." },
            { LocKey.TutKetchupDone, "Spotless! Ketchup empties one whole column." },
            { LocKey.TutMustardBody, "Free Mustard! Drop it on a column: its top two ingredients vanish everywhere!" },
            { LocKey.TutMustardDone, "Big sweep! Mustard pays off when one ingredient is everywhere." },
            { LocKey.TutSkewerBody, "Free Skewer! Drop it on the buried bun's column to dig it out." },
            { LocKey.TutSkewerDone, "Rescued and served! A buried bun is a burger waiting to happen." },
            { LocKey.TutReadyTitle, "READY!" },
            { LocKey.TutReadyBody, "Tap the Burger Fairies for more power-ups. The diner is yours!" },
            { LocKey.TutTapToContinue, "TAP TO CONTINUE" },
            { LocKey.TutSkip, "SKIP" },
            { LocKey.ShopTitle, "SHOP" },
            { LocKey.ShopDogtorSkins, "DOGTOR SKINS" },
            { LocKey.ShopIngredientSkins, "INGREDIENT SKINS" },
            { LocKey.ShopProCookPack, "PRO COOK PACK" },
            { LocKey.ShopStars, "STARS" },
            { LocKey.ShopGems, "GEMS" },
            { LocKey.ShopRemoveAds, "REMOVE ADS" },
            { LocKey.ShopRewardAds, "REWARD ADS STILL AVAILABLE" },
            { LocKey.ShopOneTimeBuy, "ONE\nTIME\nBUY" },
            { LocKey.ShopThankYou, "THANK YOU FOR\nSUPPORTING US!" },
            { LocKey.ShopWatchAd, "WATCH AD" },
            { LocKey.ShopTomorrow, "TOMORROW!" },
            { LocKey.ShopLoading, "LOADING..." },
            { LocKey.ShopRestorePurchases, "Restore Purchases" },
            { LocKey.ShopBuyAmount, "Buy {0}" },
            { LocKey.ShopForCost, "for {0}" },
            { LocKey.ShopBuy, "BUY" },
            { LocKey.ShopCancel, "CANCEL" },
            { LocKey.ShopEquipped, "EQUIPPED" },
            { LocKey.ShopEquip, "EQUIP" },
            { LocKey.StatLevel, "Level" },
            { LocKey.StatScore, "Score" },
            { LocKey.SkinChefDefault, "Classic Chef" },
            { LocKey.SkinChefBurgerchain, "Burger Chain Chef" },
            { LocKey.SkinChefEuropean, "European Chef" },
            { LocKey.SkinChefJapanese, "Japanese Chef" },
            { LocKey.SkinChefMexican, "Mexican Chef" },
            { LocKey.SkinChefRoyale, "Royale Chef" },
            { LocKey.SkinBunDefault, "Classic Bun" },
            { LocKey.SkinBunGourmet, "Integral Buns" },
            { LocKey.SkinBunGold, "Gold Buns" },
            { LocKey.SkinBunRustic, "Rustic Buns" },
            { LocKey.SkinBunBlack, "Black Bread" },
            { LocKey.SkinMeatDefault, "Classic Patty" },
            { LocKey.SkinMeatGourmet, "Chicken Burger" },
            { LocKey.SkinMeatGold, "Gold Patty" },
            { LocKey.SkinMeatVegan, "Vegan Burger" },
            { LocKey.SkinMeatWagyu, "Wagyu Steak" },
            { LocKey.SkinCheeseDefault, "Classic Cheese" },
            { LocKey.SkinCheeseGourmet, "Cheddar Cheese" },
            { LocKey.SkinCheeseGold, "Gold Cheese" },
            { LocKey.SkinCheeseShredded, "Shredded Cheese" },
            { LocKey.SkinCheeseBlue, "Blue Cheese" },
            { LocKey.SkinTomatoDefault, "Classic Tomato" },
            { LocKey.SkinTomatoGourmet, "Cherry Tomato" },
            { LocKey.SkinTomatoGold, "Gold Tomato" },
            { LocKey.SkinTomatoPico, "Pico de Gallo" },
            { LocKey.SkinTomatoKumato, "Kumato" },
            { LocKey.SkinBaconDefault, "Bacon" },
            { LocKey.SkinBaconGourmet, "Bacon Bits" },
            { LocKey.SkinBaconGold, "Gold Bacon" },
            { LocKey.SkinBaconPulledpork, "Pulled Pork" },
            { LocKey.SkinBaconIberic, "Iberic Ham" },
            { LocKey.SkinOnionDefault, "Classic Onion" },
            { LocKey.SkinOnionGourmet, "Caramelized Onion" },
            { LocKey.SkinOnionGold, "Gold Onion" },
            { LocKey.SkinOnionPickled, "Pickled Onion" },
            { LocKey.SkinOnionCrispy, "Crispy Onion" },
            { LocKey.SkinPickleDefault, "Classic Pickle" },
            { LocKey.SkinPickleGourmet, "Relish Pickles" },
            { LocKey.SkinPickleGold, "Gold Pickle" },
            { LocKey.SkinPickleBellpepper, "Bell Pepper" },
            { LocKey.SkinPickleJalapeno, "Jalapeño" },
            { LocKey.SkinLettuceDefault, "Classic Lettuce" },
            { LocKey.SkinLettuceGourmet, "Shredded Lettuce" },
            { LocKey.SkinLettuceGold, "Gold Lettuce" },
            { LocKey.SkinLettuceAvocado, "Avocado" },
            { LocKey.SkinLettucePurple, "Purple Cabbage" },
            { LocKey.SkinEggDefault, "Classic Egg" },
            { LocKey.SkinEggBoiled, "Boiled Egg" },
            { LocKey.SkinEggGold, "Gold Egg" },
            { LocKey.SkinEggGourmet, "Quail Egg" },
            { LocKey.SkinEggOmelet, "Omelet" },
        };
    }
}
