using System.Collections.Generic;

namespace DogtorBurguer
{
    /// <summary>PT strings — one entry per LocKey (Loc's editor boot check screams on gaps).
    /// Machine-drafted 2026-09-08, native-phrasing polish pass the same day.</summary>
    public static class Strings_PT
    {
        public static readonly Dictionary<LocKey, string> Table = new()
        {
            { LocKey.SettingsTitle, "AJUSTES" },
            { LocKey.SettingsSoundOn, "Som: LIGADO" },
            { LocKey.SettingsSoundOff, "Som: DESLIGADO" },
            { LocKey.SettingsMusicOn, "Música: LIGADO" },
            { LocKey.SettingsMusicOff, "Música: DESLIGADO" },
            { LocKey.SettingsControlsDrag, "Controles: Arrastar" },
            { LocKey.SettingsControlsTap, "Controles: Tocar" },
            { LocKey.SettingsStartLevel, "INÍCIO: NÍVEL {0}" },
            { LocKey.SettingsQuit, "Voltar ao Menu" },
            { LocKey.SettingsLanguage, "Idioma: {0}" },
            { LocKey.SettingsRestart, "Reiniciar" },
            { LocKey.MenuPlay, "JOGAR" },
            { LocKey.MenuResume, "CONTINUAR" },
            { LocKey.MenuCredits, "CRÉDITOS" },
            { LocKey.MenuShop, "LOJA" },
            { LocKey.MenuSupportDevs, "Apoie os devs!" },
            { LocKey.GameOverTitle, "GAME OVER..." },
            { LocKey.GameOverStarsEarned, "Você ganhou {0} estrelas!" },
            { LocKey.GameOverContinue, "Continuar" },
            { LocKey.GameOverNoMoreContinues, "Não dá mais para continuar" },
            { LocKey.GameOverWatch, "Assistir" },
            { LocKey.GameOverLoading, "Carregando..." },
            { LocKey.GameOverMainMenu, "Menu\nPrincipal" },
            { LocKey.GameOverRetry, "De novo" },
            { LocKey.HowToTitle, "COMO JOGAR" },
            { LocKey.HowToPlayTutorial, "JOGAR TUTORIAL" },
            { LocKey.HowToControls, "CONTROLES" },
            { LocKey.HowToControls1, "Deslize, ou toque à esquerda ou à direita do chef, para movê-lo." },
            { LocKey.HowToControls2, "Toque no chef para trocar as duas colunas na frente dele." },
            { LocKey.HowToControls3, "Toque num ingrediente caindo para ele cair mais rápido." },
            { LocKey.HowToControls4, "Toque num ingrediente lá de cima para soltá-lo na hora." },
            { LocKey.HowToMatching, "PARES" },
            { LocKey.HowToMatching1, "Dois ingredientes iguais empilhados estouram e dão pontos." },
            { LocKey.HowToMatching2, "Mantenha as colunas baixas: se uma transbordar, acabou!" },
            { LocKey.HowToBurgers, "HAMBÚRGUERES" },
            { LocKey.HowToBurgers1, "Abra com um pão de baixo." },
            { LocKey.HowToBurgers2, "Empilhe ingredientes em cima." },
            { LocKey.HowToBurgers3, "Feche com um pão de cima para servir o hambúrguer." },
            { LocKey.HowToBurgers4, "Hambúrgueres maiores dão mais pontos!" },
            { LocKey.HowToOrders, "PEDIDOS ESPECIAIS" },
            { LocKey.HowToOrders1, "Sirva um hambúrguer que corresponda ao pedido mostrado." },
            { LocKey.HowToOrders2, "Pedidos pagam estrelas e aumentam seu multiplicador." },
            { LocKey.PowerUps, "POWER-UPS" },
            { LocKey.HowToPowerUpsA1, "A Fada Burger traz gemas, estrelas e power-ups. Toque nela antes que vá embora!" },
            { LocKey.HowToPowerUpsA2, "Arraste um power-up do slot até uma coluna para usar." },
            { LocKey.HowToPowerUpsB1, "O ketchup limpa a coluna inteira." },
            { LocKey.HowToPowerUpsB2, "A mostarda pega os dois ingredientes do topo da coluna e varre os dois do tabuleiro inteiro." },
            { LocKey.HowToPowerUpsB3, "O espeto empurra um pão de baixo até a base da coluna." },
            { LocKey.CreditsTitle, "CRÉDITOS" },
            { LocKey.CreditsGameBy, "UM JOGO DE" },
            { LocKey.CreditsArtBy, "ARTE DE" },
            { LocKey.CreditsMusicBy, "MÚSICA DE" },
            { LocKey.SpecialOrder, "PEDIDO ESPECIAL" },
            { LocKey.MultTab, "MULT" },
            { LocKey.TooBad, "Que pena!" },
            { LocKey.OrderComplete, "Pedido completo!" },
            { LocKey.NamerGood, "Bom!" },
            { LocKey.NamerTasty, "Gostoso!" },
            { LocKey.NamerGreat, "Ótimo!" },
            { LocKey.NamerDelicious, "Delicioso!" },
            { LocKey.NamerAwesome, "Demais!!" },
            { LocKey.NamerIncredible, "Incrível!!" },
            { LocKey.NamerExquisite, "Requintado!!" },
            { LocKey.NamerGourmet, "Gourmet!!" },
            { LocKey.NamerJustBread, "Só pão..." },
            { LocKey.NamerDogtorBurger, "DOGTOR BURGER!!!" },
            { LocKey.TutMoveTitle, "MOVA-SE!" },
            { LocKey.TutMoveTap, "Toque à ESQUERDA ou à DIREITA do Dogtor para movê-lo." },
            { LocKey.TutMoveSwipe, "Deslize para a esquerda ou direita para mover o Dogtor." },
            { LocKey.TutSwapTitle, "TROQUE!" },
            { LocKey.TutSwapBody, "Toque no Dogtor para trocar as colunas da frente!" },
            { LocKey.TutMatchTitle, "PAR!" },
            { LocKey.TutMatchBody, "Dois iguais estouram! Troque para cair sobre o igual.\nPares: {0}/{1}" },
            { LocKey.TutMatchDone, "Delicioso! Os pares limpam o balcão e dão pontos." },
            { LocKey.TutFastDropTitle, "COM PRESSA?" },
            { LocKey.TutFastDropBody, "Toque num ingrediente caindo para ele descer rápido!" },
            { LocKey.TutFastDropDone, "Zum! Apresse uma peça quando precisar dela lá embaixo." },
            { LocKey.TutBurgerTitle, "HORA DO BURGER!" },
            { LocKey.TutBurgerBody, "TROQUE para tudo cair no pão de baixo! Feche com a tampa." },
            { LocKey.TutBurgerDone, "Servido! Hambúrgueres maiores dão muito mais pontos." },
            { LocKey.TutOrderTitle, "PEDIDO ESPECIAL!" },
            { LocKey.TutOrderBody, "Um cliente quer ESTE! A ordem não importa: só monte." },
            { LocKey.TutOrderDone, "Os pedidos sobem seu multiplicador em CADA ponto!" },
            { LocKey.TutPowerUpTitle, "POWER-UP!" },
            { LocKey.TutKetchupBody, "Ketchup grátis! Arraste até a coluna bagunçada." },
            { LocKey.TutKetchupDone, "Impecável! O ketchup esvazia uma coluna inteira." },
            { LocKey.TutMustardBody, "Mostarda grátis! Solte numa coluna e os dois ingredientes do topo somem do tabuleiro inteiro." },
            { LocKey.TutMustardDone, "Que varrida! A mostarda rende se um ingrediente está em tudo." },
            { LocKey.TutSkewerBody, "Espeto grátis! Solte onde o pão está enterrado." },
            { LocKey.TutSkewerDone, "Resgatado e servido! Um pão enterrado é um hambúrguer esperando." },
            { LocKey.TutReadyTitle, "PRONTO!" },
            { LocKey.TutReadyBody, "Toque nas Fadas Burger para mais power-ups! A lanchonete é sua." },
            { LocKey.TutTapToContinue, "TOQUE PARA CONTINUAR" },
            { LocKey.TutSkip, "PULAR" },
            { LocKey.ShopTitle, "LOJA" },
            { LocKey.ShopDogtorSkins, "SKINS DE DOGTOR" },
            { LocKey.ShopIngredientSkins, "SKINS DE INGREDIENTES" },
            { LocKey.ShopProCookPack, "PACOTE PRO DO CHEF" },
            { LocKey.ShopStars, "ESTRELAS" },
            { LocKey.ShopGems, "GEMAS" },
            { LocKey.ShopRemoveAds, "REMOVER ANÚNCIOS" },
            { LocKey.ShopRewardAds, "ANÚNCIOS DE RECOMPENSA CONTINUAM" },
            { LocKey.ShopOneTimeBuy, "COMPRA\nÚNICA" },
            { LocKey.ShopThankYou, "OBRIGADO POR\nNOS APOIAR!" },
            { LocKey.ShopWatchAd, "VER ANÚNCIO" },
            { LocKey.ShopTomorrow, "AMANHÃ!" },
            { LocKey.ShopLoading, "CARREGANDO..." },
            { LocKey.ShopRestorePurchases, "Restaurar compras" },
            { LocKey.ShopBuyAmount, "Comprar {0}" },
            { LocKey.ShopForCost, "por {0}" },
            { LocKey.ShopBuy, "COMPRAR" },
            { LocKey.ShopCancel, "CANCELAR" },
            { LocKey.ShopEquipped, "EQUIPADO" },
            { LocKey.ShopEquip, "EQUIPAR" },
            { LocKey.StatLevel, "Nível" },
            { LocKey.StatScore, "Pontos" },
            { LocKey.SkinChefDefault, "Chef clássico" },
            { LocKey.SkinChefBurgerchain, "Chef de franquia" },
            { LocKey.SkinChefEuropean, "Chef europeu" },
            { LocKey.SkinChefJapanese, "Chef japonês" },
            { LocKey.SkinChefMexican, "Chef mexicano" },
            { LocKey.SkinChefRoyale, "Chef Royale" },
            { LocKey.SkinBunDefault, "Pão clássico" },
            { LocKey.SkinBunGourmet, "Pão integral" },
            { LocKey.SkinBunGold, "Pão de ouro" },
            { LocKey.SkinBunRustic, "Pão rústico" },
            { LocKey.SkinBunBlack, "Pão preto" },
            { LocKey.SkinMeatDefault, "Carne clássica" },
            { LocKey.SkinMeatGourmet, "Burger de frango" },
            { LocKey.SkinMeatGold, "Carne de ouro" },
            { LocKey.SkinMeatVegan, "Burger vegano" },
            { LocKey.SkinMeatWagyu, "Bife wagyu" },
            { LocKey.SkinCheeseDefault, "Queijo clássico" },
            { LocKey.SkinCheeseGourmet, "Queijo cheddar" },
            { LocKey.SkinCheeseGold, "Queijo de ouro" },
            { LocKey.SkinCheeseShredded, "Queijo ralado" },
            { LocKey.SkinCheeseBlue, "Queijo azul" },
            { LocKey.SkinTomatoDefault, "Tomate clássico" },
            { LocKey.SkinTomatoGourmet, "Tomate-cereja" },
            { LocKey.SkinTomatoGold, "Tomate de ouro" },
            { LocKey.SkinTomatoPico, "Pico de gallo" },
            { LocKey.SkinTomatoKumato, "Kumato" },
            { LocKey.SkinBaconDefault, "Bacon" },
            { LocKey.SkinBaconGourmet, "Bacon em cubos" },
            { LocKey.SkinBaconGold, "Bacon de ouro" },
            { LocKey.SkinBaconPulledpork, "Porco desfiado" },
            { LocKey.SkinBaconIberic, "Presunto ibérico" },
            { LocKey.SkinOnionDefault, "Cebola clássica" },
            { LocKey.SkinOnionGourmet, "Cebola caramelizada" },
            { LocKey.SkinOnionGold, "Cebola de ouro" },
            { LocKey.SkinOnionPickled, "Cebola em conserva" },
            { LocKey.SkinOnionCrispy, "Cebola crocante" },
            { LocKey.SkinPickleDefault, "Picles clássico" },
            { LocKey.SkinPickleGourmet, "Picles picado" },
            { LocKey.SkinPickleGold, "Picles de ouro" },
            { LocKey.SkinPickleBellpepper, "Pimentão" },
            { LocKey.SkinPickleJalapeno, "Jalapeño" },
            { LocKey.SkinLettuceDefault, "Alface clássica" },
            { LocKey.SkinLettuceGourmet, "Alface picada" },
            { LocKey.SkinLettuceGold, "Alface de ouro" },
            { LocKey.SkinLettuceAvocado, "Abacate" },
            { LocKey.SkinLettucePurple, "Repolho roxo" },
            { LocKey.SkinEggDefault, "Ovo clássico" },
            { LocKey.SkinEggBoiled, "Ovo cozido" },
            { LocKey.SkinEggGold, "Ovo de ouro" },
            { LocKey.SkinEggGourmet, "Ovo de codorna" },
            { LocKey.SkinEggOmelet, "Omelete" },
        };
    }
}
