using System.Collections.Generic;

namespace DogtorBurguer
{
    /// <summary>ES strings — one entry per LocKey (Loc's editor boot check screams on gaps).
    /// Machine-drafted 2026-09-08, native-phrasing polish pass the same day; Oscar proofreads this one.</summary>
    public static class Strings_ES
    {
        public static readonly Dictionary<LocKey, string> Table = new()
        {
            { LocKey.SettingsTitle, "AJUSTES" },
            { LocKey.SettingsSoundOn, "Sonido: SÍ" },
            { LocKey.SettingsSoundOff, "Sonido: NO" },
            { LocKey.SettingsControlsDrag, "Controles: Arrastrar" },
            { LocKey.SettingsControlsTap, "Controles: Tocar" },
            { LocKey.SettingsStartLevel, "START: LVL {0}" },
            { LocKey.SettingsQuit, "Salir al Menú" },
            { LocKey.SettingsLanguage, "Idioma: {0}" },
            { LocKey.MenuPlay, "JUGAR" },
            { LocKey.MenuCredits, "CRÉDITOS" },
            { LocKey.MenuShop, "TIENDA" },
            { LocKey.MenuSupportDevs, "¡Apoya a los devs!" },
            { LocKey.GameOverTitle, "GAME OVER..." },
            { LocKey.GameOverStarsEarned, "¡Has ganado {0} estrellas!" },
            { LocKey.GameOverContinue, "Continuar" },
            { LocKey.GameOverNoMoreContinues, "Ya no puedes continuar" },
            { LocKey.GameOverWatch, "Ver" },
            { LocKey.GameOverLoading, "Cargando..." },
            { LocKey.GameOverMainMenu, "Menú\nPrincipal" },
            { LocKey.GameOverRetry, "Reintentar" },
            { LocKey.HowToTitle, "CÓMO JUGAR" },
            { LocKey.HowToPlayTutorial, "JUGAR TUTORIAL" },
            { LocKey.HowToControls, "CONTROLES" },
            { LocKey.HowToControls1, "- Desliza a izquierda o derecha para mover al chef." },
            { LocKey.HowToControls2, "- Toca al chef para girar sus platos." },
            { LocKey.HowToControls3, "- Toca un ingrediente que cae para acelerarlo." },
            { LocKey.HowToControls4, "- Toca una flecha de arriba para que ese ingrediente caiga ya." },
            { LocKey.HowToMatching, "PAREJAS" },
            { LocKey.HowToMatching1, "- Dos ingredientes iguales apilados explotan y dan puntos." },
            { LocKey.HowToMatching2, "- Mantén las columnas bajas: ¡si una se desborda, se acabó!" },
            { LocKey.HowToBurgers, "HAMBURGUESAS" },
            { LocKey.HowToBurgers1, "- Abre con un pan de abajo." },
            { LocKey.HowToBurgers2, "- Apila ingredientes encima." },
            { LocKey.HowToBurgers3, "- Cierra con un pan de arriba para servir la hamburguesa." },
            { LocKey.HowToBurgers4, "- ¡Las hamburguesas grandes dan más puntos!" },
            { LocKey.HowToOrders, "PEDIDOS ESPECIALES" },
            { LocKey.HowToOrders1, "- Sirve una hamburguesa que encaje con el pedido mostrado." },
            { LocKey.HowToOrders2, "- Los pedidos pagan estrellas y suben tu multiplicador." },
            { LocKey.PowerUps, "POTENCIADORES" },
            { LocKey.HowToPowerUpsA1, "- El Hada Burger trae gemas, estrellas y potenciadores. ¡Tócala antes de que se vaya!" },
            { LocKey.HowToPowerUpsA2, "- Arrastra un potenciador desde su hueco a una columna para usarlo." },
            { LocKey.HowToPowerUpsB1, "- El kétchup limpia su columna." },
            { LocKey.HowToPowerUpsB2, "- La mostaza elimina en todo el tablero los dos tipos superiores de su columna." },
            { LocKey.HowToPowerUpsB3, "- La brocheta empuja un pan de abajo hasta la base de su columna." },
            { LocKey.CreditsTitle, "CRÉDITOS" },
            { LocKey.CreditsGameBy, "UN JUEGO DE" },
            { LocKey.CreditsArtBy, "ARTE DE" },
            { LocKey.CreditsMusicBy, "MÚSICA DE" },
            { LocKey.SpecialOrder, "PEDIDO ESPECIAL" },
            { LocKey.TooBad, "¡Mala suerte!" },
            { LocKey.OrderComplete, "¡Pedido completo!" },
            { LocKey.NamerGood, "¡Bueno!" },
            { LocKey.NamerTasty, "¡Rico!" },
            { LocKey.NamerGreat, "¡Genial!" },
            { LocKey.NamerDelicious, "¡Delicioso!" },
            { LocKey.NamerAwesome, "¡¡Tremendo!!" },
            { LocKey.NamerIncredible, "¡¡Increíble!!" },
            { LocKey.NamerExquisite, "¡¡Exquisito!!" },
            { LocKey.NamerGourmet, "¡¡Gourmet!!" },
            { LocKey.NamerJustBread, "Solo pan..." },
            { LocKey.NamerDogtorBurger, "DOGTOR BURGER!!!" },
            { LocKey.TutMoveTitle, "¡MUÉVETE!" },
            { LocKey.TutMoveTap, "Toca a la IZQUIERDA o DERECHA del Dogtor para moverlo entre los mostradores." },
            { LocKey.TutMoveSwipe, "Desliza a izquierda o derecha para mover al Dogtor entre los mostradores." },
            { LocKey.TutSwapTitle, "¡CAMBIA!" },
            { LocKey.TutSwapBody, "¡Toca al Dogtor para cambiar las dos pilas que tiene delante!" },
            { LocKey.TutMatchTitle, "¡PAREJA!" },
            { LocKey.TutMatchBody, "¡Dos iguales explotan! Cambia las pilas para que la carne que cae aterrice sobre su gemela." },
            { LocKey.TutMatchDone, "¡Delicioso! Emparejar limpia el mostrador y da puntos." },
            { LocKey.TutBurgerTitle, "¡HORA DE LA BURGER!" },
            { LocKey.TutBurgerBody, "¡Tu turno! Un pan de abajo abre la hamburguesa - CAMBIA las pilas para que cada pieza caiga SOBRE él. ¡Ciérrala con el pan de arriba!" },
            { LocKey.TutBurgerDone, "¡Servida! Las hamburguesas grandes dan muchos más puntos." },
            { LocKey.TutOrderTitle, "¡PEDIDO ESPECIAL!" },
            { LocKey.TutOrderBody, "¡Un cliente quiere ESTA hamburguesa exacta! El ORDEN de los ingredientes no importa - ¡móntala y sírvela!" },
            { LocKey.TutOrderDone, "Los pedidos llenan el medidor y suben tu multiplicador - ¡para CADA punto que ganes!" },
            { LocKey.TutPowerUpTitle, "¡POTENCIADOR!" },
            { LocKey.TutPowerUpBody, "¡Un kétchup gratis! Arrástralo desde su hueco a la columna desordenada para limpiarla." },
            { LocKey.TutPowerUpDone, "¡Impecable! Las Hadas Burger traen más potenciadores - tócalas cuando pasen volando." },
            { LocKey.TutReadyTitle, "¡LISTO!" },
            { LocKey.TutReadyBody, "El restaurante es tuyo. ¡Sírvelos bien, Dogtor!" },
            { LocKey.TutTapToContinue, "TOCA PARA CONTINUAR" },
            { LocKey.TutSkip, "SALTAR" },
            { LocKey.ShopTitle, "TIENDA" },
            { LocKey.ShopDogtorSkins, "SKINS DE DOGTOR" },
            { LocKey.ShopIngredientSkins, "SKINS DE INGREDIENTES" },
            { LocKey.ShopProCookPack, "PACK PRO DEL CHEF" },
            { LocKey.ShopStars, "ESTRELLAS" },
            { LocKey.ShopGems, "GEMAS" },
            { LocKey.ShopRemoveAds, "QUITAR ANUNCIOS" },
            { LocKey.ShopRewardAds, "MANTIENES LOS ANUNCIOS CON RECOMPENSA" },
            { LocKey.ShopOneTimeBuy, "COMPRA\nÚNICA" },
            { LocKey.ShopThankYou, "¡GRACIAS POR\nAPOYARNOS!" },
            { LocKey.ShopWatchAd, "VER ANUNCIO" },
            { LocKey.ShopTomorrow, "¡MAÑANA!" },
            { LocKey.ShopLoading, "CARGANDO..." },
            { LocKey.ShopRestorePurchases, "Restaurar compras" },
            { LocKey.ShopBuyAmount, "Comprar {0}" },
            { LocKey.ShopForCost, "por {0}" },
            { LocKey.ShopBuy, "COMPRAR" },
            { LocKey.ShopCancel, "CANCELAR" },
            { LocKey.ShopEquipped, "EQUIPADO" },
            { LocKey.ShopEquip, "EQUIPAR" },
        };
    }
}
