using System.Collections.Generic;

namespace DogtorBurguer
{
    /// <summary>DE strings — one entry per LocKey (Loc's editor boot check screams on gaps).
    /// Machine-drafted 2026-09-08, native-phrasing polish pass the same day.</summary>
    public static class Strings_DE
    {
        public static readonly Dictionary<LocKey, string> Table = new()
        {
            { LocKey.SettingsTitle, "EINSTELLUNGEN" },
            { LocKey.SettingsSoundOn, "Ton: AN" },
            { LocKey.SettingsSoundOff, "Ton: AUS" },
            { LocKey.SettingsControlsDrag, "Steuerung: Ziehen" },
            { LocKey.SettingsControlsTap, "Steuerung: Tippen" },
            { LocKey.SettingsStartLevel, "START: LVL {0}" },
            { LocKey.SettingsQuit, "Zurück zum Menü" },
            { LocKey.SettingsLanguage, "Sprache: {0}" },
            { LocKey.MenuPlay, "SPIELEN" },
            { LocKey.MenuCredits, "CREDITS" },
            { LocKey.MenuShop, "SHOP" },
            { LocKey.MenuSupportDevs, "Unterstütze die Devs!" },
            { LocKey.GameOverTitle, "GAME OVER..." },
            { LocKey.GameOverStarsEarned, "{0} Sterne verdient!" },
            { LocKey.GameOverContinue, "Weiter" },
            { LocKey.GameOverNoMoreContinues, "Keine Continues mehr" },
            { LocKey.GameOverWatch, "Ansehen" },
            { LocKey.GameOverLoading, "Lädt..." },
            { LocKey.GameOverMainMenu, "Haupt-\nmenü" },
            { LocKey.GameOverRetry, "Nochmal" },
            { LocKey.HowToTitle, "SO WIRD GESPIELT" },
            { LocKey.HowToPlayTutorial, "TUTORIAL SPIELEN" },
            { LocKey.HowToControls, "STEUERUNG" },
            { LocKey.HowToControls1, "- Wische nach links oder rechts, um den Koch zu bewegen." },
            { LocKey.HowToControls2, "- Tippe auf den Koch, um seine Teller zu tauschen." },
            { LocKey.HowToControls3, "- Tippe auf eine fallende Zutat, damit sie schneller fällt." },
            { LocKey.HowToControls4, "- Tippe auf einen Vorschau-Pfeil, um die Zutat sofort fallen zu lassen." },
            { LocKey.HowToMatching, "PAARE" },
            { LocKey.HowToMatching1, "- Zwei gestapelte gleiche Zutaten platzen und geben Punkte." },
            { LocKey.HowToMatching2, "- Halte die Spalten niedrig: läuft eine über, ist Schluss!" },
            { LocKey.HowToBurgers, "BURGER" },
            { LocKey.HowToBurgers1, "- Beginne mit einem unteren Brötchen." },
            { LocKey.HowToBurgers2, "- Stapel beliebige Zutaten darauf." },
            { LocKey.HowToBurgers3, "- Schließe mit einem oberen Brötchen, um den Burger zu servieren." },
            { LocKey.HowToBurgers4, "- Größere Burger bringen mehr Punkte!" },
            { LocKey.HowToOrders, "SPEZIALBESTELLUNGEN" },
            { LocKey.HowToOrders1, "- Serviere einen Burger, der zur gezeigten Bestellung passt." },
            { LocKey.HowToOrders2, "- Bestellungen zahlen Sterne und erhöhen deinen Multiplikator." },
            { LocKey.PowerUps, "POWER-UPS" },
            { LocKey.HowToPowerUpsA1, "- Die Burger-Fee bringt Juwelen, Sterne und Power-ups. Tippe sie an, bevor sie geht!" },
            { LocKey.HowToPowerUpsA2, "- Zieh ein Power-up aus seinem Slot auf eine Spalte, um es zu benutzen." },
            { LocKey.HowToPowerUpsB1, "- Ketchup räumt seine Spalte leer." },
            { LocKey.HowToPowerUpsB2, "- Senf fegt die obersten zwei Zutatentypen seiner Spalte vom ganzen Brett." },
            { LocKey.HowToPowerUpsB3, "- Der Spieß schiebt ein unteres Brötchen bis zum Boden seiner Spalte." },
            { LocKey.CreditsTitle, "CREDITS" },
            { LocKey.CreditsGameBy, "EIN SPIEL VON" },
            { LocKey.CreditsArtBy, "GRAFIK VON" },
            { LocKey.CreditsMusicBy, "MUSIK VON" },
            { LocKey.SpecialOrder, "SPEZIALBESTELLUNG" },
            { LocKey.TooBad, "Schade!" },
            { LocKey.OrderComplete, "Bestellung fertig!" },
            { LocKey.NamerGood, "Gut!" },
            { LocKey.NamerTasty, "Lecker!" },
            { LocKey.NamerGreat, "Super!" },
            { LocKey.NamerDelicious, "Köstlich!" },
            { LocKey.NamerAwesome, "Klasse!!" },
            { LocKey.NamerIncredible, "Unglaublich!!" },
            { LocKey.NamerExquisite, "Exquisit!!" },
            { LocKey.NamerGourmet, "Gourmet!!" },
            { LocKey.NamerJustBread, "Nur Brot..." },
            { LocKey.NamerDogtorBurger, "DOGTOR BURGER!!!" },
            { LocKey.TutMoveTitle, "BEWEG DICH!" },
            { LocKey.TutMoveTap, "Tippe LINKS oder RECHTS vom Dogtor, um ihn zwischen den Theken zu bewegen." },
            { LocKey.TutMoveSwipe, "Wische nach links oder rechts, um den Dogtor zwischen den Theken zu bewegen." },
            { LocKey.TutSwapTitle, "TAUSCHEN!" },
            { LocKey.TutSwapBody, "Tippe auf den Dogtor, um die zwei Stapel vor ihm zu tauschen!" },
            { LocKey.TutMatchTitle, "MATCH!" },
            { LocKey.TutMatchBody, "Zwei Gleiche platzen! Tausche die Stapel, damit das fallende Patty auf seinem Zwilling landet." },
            { LocKey.TutMatchDone, "Köstlich! Paare räumen die Theke und geben Punkte." },
            { LocKey.TutBurgerTitle, "BURGER-ZEIT!" },
            { LocKey.TutBurgerBody, "Du bist dran! Ein unteres Brötchen öffnet den Burger - TAUSCHE die Stapel, damit jedes Teil DARAUF landet. Schließe mit dem oberen Brötchen!" },
            { LocKey.TutBurgerDone, "Serviert! Größere Burger geben viel mehr Punkte." },
            { LocKey.TutOrderTitle, "SPEZIALBESTELLUNG!" },
            { LocKey.TutOrderBody, "Ein Kunde will GENAU diesen Burger! Die REIHENFOLGE der Zutaten ist egal - bau ihn und serviere!" },
            { LocKey.TutOrderDone, "Bestellungen füllen die Anzeige und erhöhen deinen Multiplikator - für JEDEN Punkt!" },
            { LocKey.TutPowerUpTitle, "POWER-UP!" },
            { LocKey.TutPowerUpBody, "Ein gratis Ketchup! Zieh ihn aus dem Slot auf die volle Spalte, um sie zu putzen." },
            { LocKey.TutPowerUpDone, "Blitzblank! Burger-Feen bringen mehr Power-ups - tippe sie an, wenn sie vorbeifliegen." },
            { LocKey.TutReadyTitle, "BEREIT!" },
            { LocKey.TutReadyBody, "Das Diner gehört dir. Mach die Gäste glücklich, Dogtor!" },
            { LocKey.TutTapToContinue, "ZUM FORTFAHREN TIPPEN" },
            { LocKey.TutSkip, "SKIP" },
            { LocKey.ShopTitle, "SHOP" },
            { LocKey.ShopDogtorSkins, "DOGTOR-SKINS" },
            { LocKey.ShopIngredientSkins, "ZUTATEN-SKINS" },
            { LocKey.ShopProCookPack, "PROFI-KOCH-PAKET" },
            { LocKey.ShopStars, "STERNE" },
            { LocKey.ShopGems, "JUWELEN" },
            { LocKey.ShopRemoveAds, "WERBUNG ENTFERNEN" },
            { LocKey.ShopRewardAds, "BONUS-WERBUNG BLEIBT VERFÜGBAR" },
            { LocKey.ShopOneTimeBuy, "EINMAL-\nKAUF" },
            { LocKey.ShopThankYou, "DANKE FÜR DEINE\nUNTERSTÜTZUNG!" },
            { LocKey.ShopWatchAd, "WERBUNG ANSEHEN" },
            { LocKey.ShopTomorrow, "MORGEN!" },
            { LocKey.ShopLoading, "LÄDT..." },
            { LocKey.ShopRestorePurchases, "Käufe wiederherstellen" },
            { LocKey.ShopBuyAmount, "{0} kaufen" },
            { LocKey.ShopForCost, "für {0}" },
            { LocKey.ShopBuy, "KAUFEN" },
            { LocKey.ShopCancel, "ABBRECHEN" },
            { LocKey.ShopEquipped, "AKTIV" },
            { LocKey.ShopEquip, "ANLEGEN" },
        };
    }
}
