using System.Collections.Generic;

namespace DogtorBurguer
{
    /// <summary>TR strings — one entry per LocKey (Loc's editor boot check screams on gaps).
    /// Machine-drafted 2026-09-08, native-phrasing polish pass the same day.</summary>
    public static class Strings_TR
    {
        public static readonly Dictionary<LocKey, string> Table = new()
        {
            { LocKey.SettingsTitle, "AYARLAR" },
            { LocKey.SettingsSoundOn, "Ses: AÇIK" },
            { LocKey.SettingsSoundOff, "Ses: KAPALI" },
            { LocKey.SettingsControlsDrag, "Kontrol: Sürükle" },
            { LocKey.SettingsControlsTap, "Kontrol: Dokun" },
            { LocKey.SettingsStartLevel, "BAŞLANGIÇ: SEVİYE {0}" },
            { LocKey.SettingsQuit, "Menüye Dön" },
            { LocKey.SettingsLanguage, "Dil: {0}" },
            { LocKey.MenuPlay, "OYNA" },
            { LocKey.MenuCredits, "KÜNYE" },
            { LocKey.MenuShop, "MAĞAZA" },
            { LocKey.MenuSupportDevs, "Geliştiricilere destek ol!" },
            { LocKey.GameOverTitle, "GAME OVER..." },
            { LocKey.GameOverStarsEarned, "{0} yıldız kazandın!" },
            { LocKey.GameOverContinue, "Devam" },
            { LocKey.GameOverNoMoreContinues, "Devam hakkın bitti" },
            { LocKey.GameOverWatch, "İzle" },
            { LocKey.GameOverLoading, "Yükleniyor..." },
            { LocKey.GameOverMainMenu, "Ana\nMenü" },
            { LocKey.GameOverRetry, "Tekrar Dene" },
            { LocKey.HowToTitle, "NASIL OYNANIR" },
            { LocKey.HowToPlayTutorial, "EĞİTİMİ OYNA" },
            { LocKey.HowToControls, "KONTROLLER" },
            { LocKey.HowToControls1, "- Şefi hareket ettirmek için sola veya sağa kaydır." },
            { LocKey.HowToControls2, "- Tabakları döndürmek için şefe dokun." },
            { LocKey.HowToControls3, "- Düşen bir malzemeye dokunarak hızlandır." },
            { LocKey.HowToControls4, "- Hemen düşürmek için önizleme okuna dokun." },
            { LocKey.HowToMatching, "EŞLEŞTİRME" },
            { LocKey.HowToMatching1, "- Üst üste gelen iki aynı malzeme patlar ve puan verir." },
            { LocKey.HowToMatching2, "- Sütunları alçak tut: biri taşarsa oyun biter!" },
            { LocKey.HowToBurgers, "BURGERLER" },
            { LocKey.HowToBurgers1, "- Alt ekmekle başla." },
            { LocKey.HowToBurgers2, "- Üzerine malzeme yığ." },
            { LocKey.HowToBurgers3, "- Üst ekmekle kapatıp burgeri servis et." },
            { LocKey.HowToBurgers4, "- Büyük burgerler daha çok puan verir!" },
            { LocKey.HowToOrders, "ÖZEL SİPARİŞLER" },
            { LocKey.HowToOrders1, "- Gösterilen siparişe uyan bir burger servis et." },
            { LocKey.HowToOrders2, "- Siparişler yıldız kazandırır ve çarpanını yükseltir." },
            { LocKey.PowerUps, "GÜÇLENDİRMELER" },
            { LocKey.HowToPowerUpsA1, "- Burger Perisi mücevher, yıldız ve güçlendirme getirir. Gitmeden ona dokun!" },
            { LocKey.HowToPowerUpsA2, "- Kullanmak için güçlendirmeyi yuvasından bir sütuna sürükle." },
            { LocKey.HowToPowerUpsB1, "- Ketçap kendi sütununu temizler." },
            { LocKey.HowToPowerUpsB2, "- Hardal, sütunun en üstteki iki malzeme türünü tüm tahtadan süpürür." },
            { LocKey.HowToPowerUpsB3, "- Şiş, alt ekmeği sütunun dibine iter." },
            { LocKey.CreditsTitle, "KÜNYE" },
            { LocKey.CreditsGameBy, "OYUNU YAPAN" },
            { LocKey.CreditsArtBy, "ÇİZİMLER" },
            { LocKey.CreditsMusicBy, "MÜZİKLER" },
            { LocKey.SpecialOrder, "ÖZEL SİPARİŞ" },
            { LocKey.TooBad, "Tüh!" },
            { LocKey.OrderComplete, "Sipariş tamam!" },
            { LocKey.NamerGood, "İyi!" },
            { LocKey.NamerTasty, "Lezzetli!" },
            { LocKey.NamerGreat, "Harika!" },
            { LocKey.NamerDelicious, "Nefis!" },
            { LocKey.NamerAwesome, "Müthiş!!" },
            { LocKey.NamerIncredible, "İnanılmaz!!" },
            { LocKey.NamerExquisite, "Enfes!!" },
            { LocKey.NamerGourmet, "Gurme!!" },
            { LocKey.NamerJustBread, "Sadece ekmek..." },
            { LocKey.NamerDogtorBurger, "DOGTOR BURGER!!!" },
            { LocKey.TutMoveTitle, "HAREKET!" },
            { LocKey.TutMoveTap, "Dogtor'u tezgahlar arasında taşımak için SOLUNA veya SAĞINA dokun." },
            { LocKey.TutMoveSwipe, "Dogtor'u tezgahlar arasında taşımak için sola veya sağa kaydır." },
            { LocKey.TutSwapTitle, "TAKAS!" },
            { LocKey.TutSwapBody, "Önündeki iki yığını takas etmek için Dogtor'a dokun!" },
            { LocKey.TutMatchTitle, "EŞLEŞME!" },
            { LocKey.TutMatchBody, "İki aynı patlar! Düşen köfte ikizinin üstüne insin diye yığınları takas et." },
            { LocKey.TutMatchDone, "Nefis! Eşleştirme tezgahı temizler ve puan kazandırır." },
            { LocKey.TutBurgerTitle, "BURGER ZAMANI!" },
            { LocKey.TutBurgerBody, "Sıra sende! Alt ekmek burgeri açar - her parça ÜSTÜNE düşsün diye yığınları TAKAS et. Üst ekmekle kapat!" },
            { LocKey.TutBurgerDone, "Servis edildi! Büyük burgerler çok daha fazla puan verir." },
            { LocKey.TutOrderTitle, "ÖZEL SİPARİŞ!" },
            { LocKey.TutOrderBody, "Bir müşteri TAM olarak bu burgeri istiyor! Malzeme SIRASI önemli değil - yap ve servis et!" },
            { LocKey.TutOrderDone, "Siparişler göstergeyi doldurur ve çarpanını yükseltir - kazandığın HER puan için!" },
            { LocKey.TutPowerUpTitle, "GÜÇLENDİRME!" },
            { LocKey.TutPowerUpBody, "Bedava ketçap! Dağınık sütunu temizlemek için yuvasından sürükle." },
            { LocKey.TutPowerUpDone, "Pırıl pırıl! Burger Perileri daha çok güçlendirme getirir - uçarken onlara dokun." },
            { LocKey.TutReadyTitle, "HAZIR!" },
            { LocKey.TutReadyBody, "Restoran senin. Onlara iyi hizmet et, Dogtor!" },
            { LocKey.TutTapToContinue, "DEVAM İÇİN DOKUN" },
            { LocKey.TutSkip, "GEÇ" },
            { LocKey.ShopTitle, "MAĞAZA" },
            { LocKey.ShopDogtorSkins, "DOGTOR KOSTÜMLERİ" },
            { LocKey.ShopIngredientSkins, "MALZEME KOSTÜMLERİ" },
            { LocKey.ShopProCookPack, "PRO ŞEF PAKETİ" },
            { LocKey.ShopStars, "YILDIZLAR" },
            { LocKey.ShopGems, "MÜCEVHERLER" },
            { LocKey.ShopRemoveAds, "REKLAMLARI KALDIR" },
            { LocKey.ShopRewardAds, "ÖDÜLLÜ REKLAMLAR KAYBOLMAZ" },
            { LocKey.ShopOneTimeBuy, "TEK\nSEFERLİK" },
            { LocKey.ShopThankYou, "DESTEĞİN İÇİN\nTEŞEKKÜRLER!" },
            { LocKey.ShopWatchAd, "REKLAM İZLE" },
            { LocKey.ShopTomorrow, "YARIN!" },
            { LocKey.ShopLoading, "YÜKLENİYOR..." },
            { LocKey.ShopRestorePurchases, "Satın alımları geri yükle" },
            { LocKey.ShopBuyAmount, "{0} satın al" },
            { LocKey.ShopForCost, "fiyatı: {0}" },
            { LocKey.ShopBuy, "AL" },
            { LocKey.ShopCancel, "İPTAL" },
            { LocKey.ShopEquipped, "TAKILI" },
            { LocKey.ShopEquip, "TAK" },
            { LocKey.StatLevel, "Seviye" },
            { LocKey.StatScore, "Puan" },
        };
    }
}
