using System.Collections.Generic;

namespace DogtorBurguer
{
    /// <summary>FR strings — one entry per LocKey (Loc's editor boot check screams on gaps).
    /// Machine-drafted 2026-09-08, native-phrasing polish pass the same day.</summary>
    public static class Strings_FR
    {
        public static readonly Dictionary<LocKey, string> Table = new()
        {
            { LocKey.SettingsTitle, "RÉGLAGES" },
            { LocKey.SettingsSoundOn, "Son: ON" },
            { LocKey.SettingsSoundOff, "Son: OFF" },
            { LocKey.SettingsControlsDrag, "Contrôles: Glisser" },
            { LocKey.SettingsControlsTap, "Contrôles: Toucher" },
            { LocKey.SettingsStartLevel, "DÉBUT: NIVEAU {0}" },
            { LocKey.SettingsQuit, "Retour au Menu" },
            { LocKey.SettingsLanguage, "Langue: {0}" },
            { LocKey.SettingsRestart, "Recommencer" },
            { LocKey.MenuPlay, "JOUER" },
            { LocKey.MenuCredits, "CRÉDITS" },
            { LocKey.MenuShop, "BOUTIQUE" },
            { LocKey.MenuSupportDevs, "Soutiens les devs!" },
            { LocKey.GameOverTitle, "GAME OVER..." },
            { LocKey.GameOverStarsEarned, "{0} étoiles gagnées!" },
            { LocKey.GameOverContinue, "Continuer" },
            { LocKey.GameOverNoMoreContinues, "Plus de continues" },
            { LocKey.GameOverWatch, "Regarder" },
            { LocKey.GameOverLoading, "Chargement..." },
            { LocKey.GameOverMainMenu, "Menu\nPrincipal" },
            { LocKey.GameOverRetry, "Réessayer" },
            { LocKey.HowToTitle, "COMMENT JOUER" },
            { LocKey.HowToPlayTutorial, "LANCER LE TUTO" },
            { LocKey.HowToControls, "CONTRÔLES" },
            { LocKey.HowToControls1, "- Glisse à gauche ou à droite pour déplacer le chef." },
            { LocKey.HowToControls2, "- Touche le chef pour échanger ses assiettes." },
            { LocKey.HowToControls3, "- Touche un ingrédient qui tombe pour l'accélérer." },
            { LocKey.HowToControls4, "- Touche une flèche d'aperçu pour faire tomber l'ingrédient tout de suite." },
            { LocKey.HowToMatching, "PAIRES" },
            { LocKey.HowToMatching1, "- Deux ingrédients identiques empilés éclatent et rapportent des points." },
            { LocKey.HowToMatching2, "- Garde les colonnes basses: si une déborde, c'est fini!" },
            { LocKey.HowToBurgers, "BURGERS" },
            { LocKey.HowToBurgers1, "- Ouvre avec un pain du bas." },
            { LocKey.HowToBurgers2, "- Empile des ingrédients dessus." },
            { LocKey.HowToBurgers3, "- Ferme avec un pain du haut pour servir le burger." },
            { LocKey.HowToBurgers4, "- Les gros burgers rapportent plus!" },
            { LocKey.HowToOrders, "COMMANDES SPÉCIALES" },
            { LocKey.HowToOrders1, "- Sers un burger qui correspond à la commande affichée." },
            { LocKey.HowToOrders2, "- Les commandes paient des étoiles et montent ton multiplicateur." },
            { LocKey.PowerUps, "POWER-UPS" },
            { LocKey.HowToPowerUpsA1, "- La Fée Burger apporte gemmes, étoiles et power-ups. Touche-la avant qu'elle parte!" },
            { LocKey.HowToPowerUpsA2, "- Fais glisser un power-up de son emplacement vers une colonne pour l'utiliser." },
            { LocKey.HowToPowerUpsB1, "- Le ketchup vide sa colonne." },
            { LocKey.HowToPowerUpsB2, "- La moutarde balaie du plateau entier les deux types du haut de sa colonne." },
            { LocKey.HowToPowerUpsB3, "- La brochette pousse un pain du bas jusqu'à la base de sa colonne." },
            { LocKey.CreditsTitle, "CRÉDITS" },
            { LocKey.CreditsGameBy, "UN JEU DE" },
            { LocKey.CreditsArtBy, "GRAPHISMES DE" },
            { LocKey.CreditsMusicBy, "MUSIQUE DE" },
            { LocKey.SpecialOrder, "COMMANDE SPÉCIALE" },
            { LocKey.TooBad, "Dommage!" },
            { LocKey.OrderComplete, "Commande servie!" },
            { LocKey.NamerGood, "Bien!" },
            { LocKey.NamerTasty, "Savoureux!" },
            { LocKey.NamerGreat, "Génial!" },
            { LocKey.NamerDelicious, "Délicieux!" },
            { LocKey.NamerAwesome, "Énorme!!" },
            { LocKey.NamerIncredible, "Incroyable!!" },
            { LocKey.NamerExquisite, "Exquis!!" },
            { LocKey.NamerGourmet, "Gourmet!!" },
            { LocKey.NamerJustBread, "Que du pain..." },
            { LocKey.NamerDogtorBurger, "DOGTOR BURGER!!!" },
            { LocKey.TutMoveTitle, "BOUGE!" },
            { LocKey.TutMoveTap, "Touche à GAUCHE ou à DROITE du Dogtor pour le déplacer entre les comptoirs." },
            { LocKey.TutMoveSwipe, "Glisse à gauche ou à droite pour déplacer le Dogtor entre les comptoirs." },
            { LocKey.TutSwapTitle, "ÉCHANGE!" },
            { LocKey.TutSwapBody, "Touche le Dogtor pour échanger les deux piles devant lui!" },
            { LocKey.TutMatchTitle, "PAIRE!" },
            { LocKey.TutMatchBody, "Deux identiques éclatent! Échange les piles pour que le steak qui tombe atterrisse sur son jumeau." },
            { LocKey.TutMatchDone, "Délicieux! Les paires nettoient le comptoir et rapportent des points." },
            { LocKey.TutBurgerTitle, "BURGER TIME!" },
            { LocKey.TutBurgerBody, "À toi! Un pain du bas ouvre le burger - ÉCHANGE les piles pour que chaque pièce tombe DESSUS. Ferme-le avec le pain du haut!" },
            { LocKey.TutBurgerDone, "Servi! Les gros burgers rapportent bien plus." },
            { LocKey.TutOrderTitle, "COMMANDE SPÉCIALE!" },
            { LocKey.TutOrderBody, "Un client veut EXACTEMENT ce burger! L'ORDRE des ingrédients ne compte pas - monte-le et sers-le!" },
            { LocKey.TutOrderDone, "Les commandes remplissent la jauge et montent ton multiplicateur - pour CHAQUE point gagné!" },
            { LocKey.TutPowerUpTitle, "POWER-UP!" },
            { LocKey.TutPowerUpBody, "Un ketchup gratuit! Fais-le glisser de son emplacement vers la colonne encombrée pour la nettoyer." },
            { LocKey.TutPowerUpDone, "Impeccable! Les Fées Burger apportent plus de power-ups - touche-les quand elles passent." },
            { LocKey.TutReadyTitle, "PRÊT!" },
            { LocKey.TutReadyBody, "Le resto est à toi. Sers-les bien, Dogtor!" },
            { LocKey.TutTapToContinue, "TOUCHE POUR CONTINUER" },
            { LocKey.TutSkip, "PASSER" },
            { LocKey.ShopTitle, "BOUTIQUE" },
            { LocKey.ShopDogtorSkins, "SKINS DOGTOR" },
            { LocKey.ShopIngredientSkins, "SKINS INGRÉDIENTS" },
            { LocKey.ShopProCookPack, "PACK PRO DU CHEF" },
            { LocKey.ShopStars, "ÉTOILES" },
            { LocKey.ShopGems, "GEMMES" },
            { LocKey.ShopRemoveAds, "SUPPRIMER LES PUBS" },
            { LocKey.ShopRewardAds, "LES PUBS BONUS RESTENT DISPONIBLES" },
            { LocKey.ShopOneTimeBuy, "ACHAT\nUNIQUE" },
            { LocKey.ShopThankYou, "MERCI DE NOUS\nSOUTENIR!" },
            { LocKey.ShopWatchAd, "VOIR LA PUB" },
            { LocKey.ShopTomorrow, "DEMAIN!" },
            { LocKey.ShopLoading, "CHARGEMENT..." },
            { LocKey.ShopRestorePurchases, "Restaurer les achats" },
            { LocKey.ShopBuyAmount, "Acheter {0}" },
            { LocKey.ShopForCost, "pour {0}" },
            { LocKey.ShopBuy, "ACHETER" },
            { LocKey.ShopCancel, "ANNULER" },
            { LocKey.ShopEquipped, "ÉQUIPÉ" },
            { LocKey.ShopEquip, "ÉQUIPER" },
            { LocKey.StatLevel, "Niveau" },
            { LocKey.StatScore, "Score" },
        };
    }
}
