using System.Collections.Generic;

namespace DogtorBurguer
{
    /// <summary>ES strings — one entry per LocKey (Loc's editor boot check screams on gaps).
    /// Machine-drafted 2026-09-08, native-phrasing polish pass the same day; Oscar proofreads this one.</summary>
    public static class Strings_ES
    {
        public static readonly Dictionary<LocKey, string> Table = new()
        {
            { LocKey.SettingsTitle, "AJUSTES" },
            { LocKey.SettingsSoundOn, "Sonido: SÍ" },
            { LocKey.SettingsSoundOff, "Sonido: NO" },
            { LocKey.SettingsMusicOn, "Música: SÍ" },
            { LocKey.SettingsMusicOff, "Música: NO" },
            { LocKey.SettingsControlsDrag, "Controles: Arrastrar" },
            { LocKey.SettingsControlsTap, "Controles: Tocar" },
            { LocKey.SettingsStartLevel, "INICIO: NIVEL {0}" },
            { LocKey.SettingsQuit, "Salir al Menú" },
            { LocKey.SettingsLanguage, "Idioma: {0}" },
            { LocKey.SettingsRestart, "Reiniciar" },
            { LocKey.MenuPlay, "JUGAR" },
            { LocKey.MenuResume, "CONTINUAR" },
            { LocKey.MenuCredits, "CRÉDITOS" },
            { LocKey.MenuShop, "TIENDA" },
            { LocKey.MenuSupportDevs, "¡Apoya a los devs!" },
            { LocKey.GameOverTitle, "GAME OVER..." },
            { LocKey.GameOverStarsEarned, "¡Has ganado {0} estrellas!" },
            { LocKey.GameOverContinue, "Continuar" },
            { LocKey.GameOverNoMoreContinues, "Ya no puedes continuar" },
            { LocKey.GameOverWatch, "Ver" },
            { LocKey.GameOverLoading, "Cargando..." },
            { LocKey.GameOverMainMenu, "Menú\nPrincipal" },
            { LocKey.GameOverRetry, "Reintentar" },
            { LocKey.HowToTitle, "CÓMO JUGAR" },
            { LocKey.HowToPlayTutorial, "JUGAR TUTORIAL" },
            { LocKey.HowToControls, "CONTROLES" },
            { LocKey.HowToControls1, "- Desliza, o toca a la izquierda o derecha del chef, para moverlo." },
            { LocKey.HowToControls2, "- Toca al chef para cambiar las dos columnas que tiene delante." },
            { LocKey.HowToControls3, "- Toca un ingrediente que cae para acelerarlo." },
            { LocKey.HowToControls4, "- Toca un ingrediente de arriba para soltarlo al momento." },
            { LocKey.HowToMatching, "PAREJAS" },
            { LocKey.HowToMatching1, "- Dos ingredientes iguales apilados explotan y dan puntos." },
            { LocKey.HowToMatching2, "- Mantén las columnas bajas: ¡si una se desborda, se acabó!" },
            { LocKey.HowToBurgers, "HAMBURGUESAS" },
            { LocKey.HowToBurgers1, "- Abre con un pan de abajo." },
            { LocKey.HowToBurgers2, "- Apila ingredientes encima." },
            { LocKey.HowToBurgers3, "- Cierra con un pan de arriba para servir la hamburguesa." },
            { LocKey.HowToBurgers4, "- ¡Las hamburguesas grandes dan más puntos!" },
            { LocKey.HowToOrders, "PEDIDOS ESPECIALES" },
            { LocKey.HowToOrders1, "- Sirve una hamburguesa que encaje con el pedido mostrado." },
            { LocKey.HowToOrders2, "- Los pedidos pagan estrellas y suben tu multiplicador." },
            { LocKey.PowerUps, "POTENCIADORES" },
            { LocKey.HowToPowerUpsA1, "- El Hada Burger trae gemas, estrellas y potenciadores. ¡Tócala antes de que se vaya!" },
            { LocKey.HowToPowerUpsA2, "- Arrastra un potenciador desde su hueco a una columna para usarlo." },
            { LocKey.HowToPowerUpsB1, "- El kétchup limpia su columna." },
            { LocKey.HowToPowerUpsB2, "- La mostaza coge los dos ingredientes de arriba de su columna y los barre de todo el tablero." },
            { LocKey.HowToPowerUpsB3, "- La brocheta empuja un pan de abajo hasta la base de su columna." },
            { LocKey.CreditsTitle, "CRÉDITOS" },
            { LocKey.CreditsGameBy, "UN JUEGO DE" },
            { LocKey.CreditsArtBy, "ARTE DE" },
            { LocKey.CreditsMusicBy, "MÚSICA DE" },
            { LocKey.SpecialOrder, "PEDIDO ESPECIAL" },
            { LocKey.TooBad, "¡Mala suerte!" },
            { LocKey.OrderComplete, "¡Pedido completo!" },
            { LocKey.NamerGood, "¡Bueno!" },
            { LocKey.NamerTasty, "¡Rico!" },
            { LocKey.NamerGreat, "¡Genial!" },
            { LocKey.NamerDelicious, "¡Delicioso!" },
            { LocKey.NamerAwesome, "¡¡Tremendo!!" },
            { LocKey.NamerIncredible, "¡¡Increíble!!" },
            { LocKey.NamerExquisite, "¡¡Exquisito!!" },
            { LocKey.NamerGourmet, "¡¡Gourmet!!" },
            { LocKey.NamerJustBread, "Solo pan..." },
            { LocKey.NamerDogtorBurger, "DOGTOR BURGER!!!" },
            { LocKey.TutMoveTitle, "¡MUÉVETE!" },
            { LocKey.TutMoveTap, "Toca a la IZQUIERDA o la DERECHA del Dogtor para moverlo." },
            { LocKey.TutMoveSwipe, "Desliza a izquierda o derecha para mover al Dogtor." },
            { LocKey.TutSwapTitle, "¡CAMBIA!" },
            { LocKey.TutSwapBody, "¡Toca al Dogtor para cambiar las columnas de delante!" },
            { LocKey.TutMatchTitle, "¡PAREJA!" },
            { LocKey.TutMatchBody, "¡Dos iguales explotan! Cambia para que caiga sobre su pareja.\nParejas: {0}/{1}" },
            { LocKey.TutMatchDone, "¡Delicioso! Las parejas limpian el mostrador y dan puntos." },
            { LocKey.TutFastDropTitle, "¿CON PRISA?" },
            { LocKey.TutFastDropBody, "¡Toca un ingrediente que cae para que baje rápido!" },
            { LocKey.TutFastDropDone, "¡Zas! Acelera una pieza cuando la necesites abajo." },
            { LocKey.TutBurgerTitle, "¡HORA DE LA BURGER!" },
            { LocKey.TutBurgerBody, "¡CAMBIA para que todo caiga sobre el pan! Ciérrala con la tapa." },
            { LocKey.TutBurgerDone, "¡Servida! Las hamburguesas grandes dan muchos más puntos." },
            { LocKey.TutOrderTitle, "¡PEDIDO ESPECIAL!" },
            { LocKey.TutOrderBody, "¡Un cliente quiere ESTA! El orden da igual: solo constrúyela." },
            { LocKey.TutOrderDone, "¡Los pedidos suben tu multiplicador en CADA punto!" },
            { LocKey.TutPowerUpTitle, "¡POTENCIADOR!" },
            { LocKey.TutKetchupBody, "¡Kétchup gratis! Arrástralo a la columna atascada." },
            { LocKey.TutKetchupDone, "¡Impecable! El kétchup vacía una columna entera." },
            { LocKey.TutMustardBody, "¡Mostaza gratis! Borra sus DOS de arriba de todo el mostrador." },
            { LocKey.TutMustardDone, "¡Barrido! La mostaza rinde si un ingrediente está por todas partes." },
            { LocKey.TutSkewerBody, "¡Pincho gratis! Suéltalo donde el pan está enterrado." },
            { LocKey.TutSkewerDone, "¡Rescatado! El pan vuelve abajo, listo para rellenar." },
            { LocKey.TutReadyTitle, "¡LISTO!" },
            { LocKey.TutReadyBody, "¡Toca a las Hadas Burger para más potenciadores! El local es tuyo." },
            { LocKey.TutTapToContinue, "TOCA PARA CONTINUAR" },
            { LocKey.TutSkip, "SALTAR" },
            { LocKey.ShopTitle, "TIENDA" },
            { LocKey.ShopDogtorSkins, "SKINS DE DOGTOR" },
            { LocKey.ShopIngredientSkins, "SKINS DE INGREDIENTES" },
            { LocKey.ShopProCookPack, "PACK PRO DEL CHEF" },
            { LocKey.ShopStars, "ESTRELLAS" },
            { LocKey.ShopGems, "GEMAS" },
            { LocKey.ShopRemoveAds, "QUITAR ANUNCIOS" },
            { LocKey.ShopRewardAds, "LOS ANUNCIOS CON RECOMPENSA SIGUEN" },
            { LocKey.ShopOneTimeBuy, "COMPRA\nÚNICA" },
            { LocKey.ShopThankYou, "¡GRACIAS POR\nAPOYARNOS!" },
            { LocKey.ShopWatchAd, "VER ANUNCIO" },
            { LocKey.ShopTomorrow, "¡MAÑANA!" },
            { LocKey.ShopLoading, "CARGANDO..." },
            { LocKey.ShopRestorePurchases, "Restaurar compras" },
            { LocKey.ShopBuyAmount, "Comprar {0}" },
            { LocKey.ShopForCost, "por {0}" },
            { LocKey.ShopBuy, "COMPRAR" },
            { LocKey.ShopCancel, "CANCELAR" },
            { LocKey.ShopEquipped, "EQUIPADO" },
            { LocKey.ShopEquip, "EQUIPAR" },
            { LocKey.StatLevel, "Nivel" },
            { LocKey.StatScore, "Puntos" },
        };
    }
}
