using System.Collections.Generic;

namespace DogtorBurguer
{
    /// <summary>IT strings — one entry per LocKey (Loc's editor boot check screams on gaps).
    /// Machine-drafted 2026-09-08.</summary>
    public static class Strings_IT
    {
        public static readonly Dictionary<LocKey, string> Table = new()
        {
            { LocKey.SettingsTitle, "IMPOSTAZIONI" },
            { LocKey.SettingsSoundOn, "Audio: SÌ" },
            { LocKey.SettingsSoundOff, "Audio: NO" },
            { LocKey.SettingsControlsDrag, "Controlli: Trascina" },
            { LocKey.SettingsControlsTap, "Controlli: Tocca" },
            { LocKey.SettingsStartLevel, "INIZIO: LIV {0}" },
            { LocKey.SettingsQuit, "Torna al Menu" },
            { LocKey.SettingsLanguage, "Lingua: {0}" },
            { LocKey.MenuPlay, "GIOCA" },
            { LocKey.MenuCredits, "CREDITI" },
            { LocKey.MenuShop, "NEGOZIO" },
            { LocKey.MenuSupportDevs, "Sostieni i dev!" },
            { LocKey.GameOverTitle, "GAME OVER..." },
            { LocKey.GameOverStarsEarned, "{0} stelle guadagnate!" },
            { LocKey.GameOverContinue, "Continua" },
            { LocKey.GameOverNoMoreContinues, "Niente più continue" },
            { LocKey.GameOverWatch, "Guarda" },
            { LocKey.GameOverLoading, "Caricamento..." },
            { LocKey.GameOverMainMenu, "Menu\nPrincipale" },
            { LocKey.GameOverRetry, "Riprova" },
            { LocKey.HowToTitle, "COME SI GIOCA" },
            { LocKey.HowToPlayTutorial, "GIOCA TUTORIAL" },
            { LocKey.HowToControls, "CONTROLLI" },
            { LocKey.HowToControls1, "- Scorri a sinistra o destra per muovere lo chef." },
            { LocKey.HowToControls2, "- Tocca lo chef per ruotare i piatti." },
            { LocKey.HowToControls3, "- Tocca un ingrediente in caduta per accelerarlo." },
            { LocKey.HowToControls4, "- Tocca una freccia di anteprima per farlo scendere subito." },
            { LocKey.HowToMatching, "COPPIE" },
            { LocKey.HowToMatching1, "- Due ingredienti uguali impilati scoppiano e danno punti." },
            { LocKey.HowToMatching2, "- Tieni basse le colonne: se una trabocca, è finita!" },
            { LocKey.HowToBurgers, "BURGER" },
            { LocKey.HowToBurgers1, "- Apri con un pane inferiore." },
            { LocKey.HowToBurgers2, "- Impila ingredienti sopra." },
            { LocKey.HowToBurgers3, "- Chiudi con un pane superiore per servire il burger." },
            { LocKey.HowToBurgers4, "- I burger più grandi valgono di più!" },
            { LocKey.HowToOrders, "ORDINI SPECIALI" },
            { LocKey.HowToOrders1, "- Servi un burger che corrisponda all'ordine mostrato." },
            { LocKey.HowToOrders2, "- Gli ordini pagano stelle e alzano il moltiplicatore." },
            { LocKey.PowerUps, "POWER-UP" },
            { LocKey.HowToPowerUpsA1, "- La Fata Burger porta gemme, stelle e power-up. Toccala prima che vada via!" },
            { LocKey.HowToPowerUpsA2, "- Trascina un power-up dal suo slot su una colonna per usarlo." },
            { LocKey.HowToPowerUpsB1, "- Il ketchup svuota la sua colonna." },
            { LocKey.HowToPowerUpsB2, "- La senape spazza dall'intero tabellone i due tipi in cima alla colonna." },
            { LocKey.HowToPowerUpsB3, "- Lo spiedino spinge un pane inferiore fino alla base della colonna." },
            { LocKey.CreditsTitle, "CREDITI" },
            { LocKey.CreditsGameBy, "UN GIOCO DI" },
            { LocKey.CreditsArtBy, "ARTE DI" },
            { LocKey.CreditsMusicBy, "MUSICA DI" },
            { LocKey.SpecialOrder, "ORDINE SPECIALE" },
            { LocKey.TooBad, "Peccato!" },
            { LocKey.OrderComplete, "Ordine completato!" },
            { LocKey.NamerGood, "Buono!" },
            { LocKey.NamerTasty, "Gustoso!" },
            { LocKey.NamerGreat, "Ottimo!" },
            { LocKey.NamerDelicious, "Delizioso!" },
            { LocKey.NamerAwesome, "Fantastico!!" },
            { LocKey.NamerIncredible, "Incredibile!!" },
            { LocKey.NamerExquisite, "Squisito!!" },
            { LocKey.NamerGourmet, "Gourmet!!" },
            { LocKey.NamerJustBread, "Solo pane..." },
            { LocKey.NamerDogtorBurger, "DOGTOR BURGER!!!" },
            { LocKey.TutMoveTitle, "MUOVITI!" },
            { LocKey.TutMoveTap, "Tocca a SINISTRA o DESTRA del Dogtor per spostarlo tra i banconi." },
            { LocKey.TutMoveSwipe, "Scorri a sinistra o destra per spostare il Dogtor tra i banconi." },
            { LocKey.TutSwapTitle, "SCAMBIA!" },
            { LocKey.TutSwapBody, "Tocca il Dogtor per scambiare le due pile davanti a lui!" },
            { LocKey.TutMatchTitle, "COPPIA!" },
            { LocKey.TutMatchBody, "Due uguali scoppiano! Scambia le pile così la carne che cade atterra sulla gemella." },
            { LocKey.TutMatchDone, "Delizioso! Le coppie puliscono il bancone e danno punti." },
            { LocKey.TutBurgerTitle, "BURGER TIME!" },
            { LocKey.TutBurgerBody, "Tocca a te! Un pane inferiore apre il burger - SCAMBIA le pile così ogni pezzo cade SOPRA. Chiudi con il pane superiore!" },
            { LocKey.TutBurgerDone, "Servito! I burger più grandi valgono molto di più." },
            { LocKey.TutOrderTitle, "ORDINE SPECIALE!" },
            { LocKey.TutOrderBody, "Un cliente vuole ESATTAMENTE questo burger! L'ORDINE degli ingredienti non conta - preparalo e servilo!" },
            { LocKey.TutOrderDone, "Gli ordini riempiono l'indicatore e alzano il moltiplicatore - per OGNI punto!" },
            { LocKey.TutPowerUpTitle, "POWER-UP!" },
            { LocKey.TutPowerUpBody, "Un ketchup gratis! Trascinalo dal suo slot sulla colonna piena per pulirla." },
            { LocKey.TutPowerUpDone, "Impeccabile! Le Fate Burger portano altri power-up - toccale quando passano." },
            { LocKey.TutReadyTitle, "PRONTO!" },
            { LocKey.TutReadyBody, "Il diner è tuo. Servili bene, Dogtor!" },
            { LocKey.TutTapToContinue, "TOCCA PER CONTINUARE" },
            { LocKey.TutSkip, "SALTA" },
            { LocKey.ShopTitle, "NEGOZIO" },
            { LocKey.ShopDogtorSkins, "SKIN DOGTOR" },
            { LocKey.ShopIngredientSkins, "SKIN INGREDIENTI" },
            { LocKey.ShopProCookPack, "PACCHETTO PRO CHEF" },
            { LocKey.ShopStars, "STELLE" },
            { LocKey.ShopGems, "GEMME" },
            { LocKey.ShopRemoveAds, "RIMUOVI PUBBLICITÀ" },
            { LocKey.ShopRewardAds, "GLI ANNUNCI PREMIO RESTANO DISPONIBILI" },
            { LocKey.ShopOneTimeBuy, "ACQUISTO\nUNICO" },
            { LocKey.ShopThankYou, "GRAZIE PER IL\nTUO SOSTEGNO!" },
            { LocKey.ShopWatchAd, "GUARDA SPOT" },
            { LocKey.ShopTomorrow, "DOMANI!" },
            { LocKey.ShopLoading, "CARICAMENTO..." },
            { LocKey.ShopRestorePurchases, "Ripristina acquisti" },
            { LocKey.ShopBuyAmount, "Compra {0}" },
            { LocKey.ShopForCost, "per {0}" },
            { LocKey.ShopBuy, "COMPRA" },
            { LocKey.ShopCancel, "ANNULLA" },
            { LocKey.ShopEquipped, "IN USO" },
            { LocKey.ShopEquip, "USA" },
        };
    }
}
