using System.Collections.Generic;

namespace DogtorBurguer
{
    /// <summary>DE strings — one entry per LocKey (Loc's editor boot check screams on gaps).
    /// Machine-drafted 2026-09-08, native-phrasing polish pass the same day.</summary>
    public static class Strings_DE
    {
        public static readonly Dictionary<LocKey, string> Table = new()
        {
            { LocKey.SettingsTitle, "EINSTELLUNGEN" },
            { LocKey.SettingsSoundOn, "Ton: AN" },
            { LocKey.SettingsSoundOff, "Ton: AUS" },
            { LocKey.SettingsMusicOn, "Musik: AN" },
            { LocKey.SettingsMusicOff, "Musik: AUS" },
            { LocKey.SettingsControlsDrag, "Steuerung: Ziehen" },
            { LocKey.SettingsControlsTap, "Steuerung: Tippen" },
            { LocKey.SettingsPrivacy, "Datenschutz" },
            { LocKey.SettingsQuit, "Zurück zum Menü" },
            { LocKey.SettingsLanguage, "Sprache: {0}" },
            { LocKey.SettingsRestart, "Neu starten" },
            { LocKey.MenuPlay, "SPIELEN" },
            { LocKey.MenuResume, "FORTSETZEN" },
            { LocKey.MenuCredits, "CREDITS" },
            { LocKey.MenuShop, "SHOP" },
            { LocKey.MenuSupportDevs, "Unterstütze die Devs!" },
            { LocKey.GameOverTitle, "GAME OVER..." },
            { LocKey.GameOverStarsEarned, "Du hast {0} Sterne verdient!" },
            { LocKey.GameOverContinue, "Weiter" },
            { LocKey.GameOverNoMoreContinues, "Keine Continues mehr" },
            { LocKey.GameOverWatch, "Ansehen" },
            { LocKey.GameOverLoading, "Lädt..." },
            { LocKey.GameOverMainMenu, "Haupt-\nmenü" },
            { LocKey.GameOverRetry, "Nochmal" },
            { LocKey.HowToTitle, "SO WIRD GESPIELT" },
            { LocKey.HowToPlayTutorial, "TUTORIAL SPIELEN" },
            { LocKey.HowToControls, "STEUERUNG" },
            { LocKey.HowToControls1, "Wische, oder tippe links oder rechts vom Koch, um ihn zu bewegen." },
            { LocKey.HowToControls2, "Tippe auf den Koch, um die zwei Stapel vor ihm zu tauschen." },
            { LocKey.HowToControls3, "Tippe auf eine fallende Zutat, damit sie schneller fällt." },
            { LocKey.HowToControls4, "Tippe oben auf eine kommende Zutat, um sie sofort fallen zu lassen." },
            { LocKey.HowToMatching, "PAARE" },
            { LocKey.HowToMatching1, "Zwei gestapelte gleiche Zutaten platzen und geben Punkte." },
            { LocKey.HowToMatching2, "Halte die Spalten niedrig: läuft eine über, ist Schluss!" },
            { LocKey.HowToBurgers, "BURGER" },
            { LocKey.HowToBurgers1, "Beginne mit einem unteren Brötchen." },
            { LocKey.HowToBurgers2, "Leg beliebige Zutaten darauf." },
            { LocKey.HowToBurgers3, "Schließe mit einem oberen Brötchen, um den Burger zu servieren." },
            { LocKey.HowToBurgers4, "Größere Burger bringen mehr Punkte!" },
            { LocKey.HowToOrders, "SPEZIALBESTELLUNGEN" },
            { LocKey.HowToOrders1, "Serviere einen Burger, der zur gezeigten Bestellung passt." },
            { LocKey.HowToOrders2, "Bestellungen bringen Sterne und erhöhen deinen Multiplikator." },
            { LocKey.PowerUps, "POWER-UPS" },
            { LocKey.HowToPowerUpsA1, "Die Burger-Fee bringt Juwelen, Sterne und Power-ups. Tippe sie an, bevor sie geht!" },
            { LocKey.HowToPowerUpsA2, "Zieh ein Power-up aus seinem Slot auf eine Spalte, um es zu benutzen." },
            { LocKey.HowToPowerUpsB1, "Ketchup leert seine ganze Spalte." },
            { LocKey.HowToPowerUpsB2, "Senf nimmt die zwei obersten Zutatentypen seiner Spalte und fegt sie vom ganzen Spielfeld." },
            { LocKey.HowToPowerUpsB3, "Der Spieß schiebt ein unteres Brötchen bis zum Boden seiner Spalte." },
            { LocKey.CreditsTitle, "CREDITS" },
            { LocKey.CreditsGameBy, "EIN SPIEL VON" },
            { LocKey.CreditsArtBy, "GRAFIK VON" },
            { LocKey.CreditsMusicBy, "MUSIK VON" },
            { LocKey.SpecialOrder, "SPEZIALBESTELLUNG" },
            { LocKey.MultTab, "MULT" },
            { LocKey.TooBad, "Schade!" },
            { LocKey.NewIngredient, "NEUE ZUTAT!" },
            { LocKey.OrderComplete, "Bestellung fertig!" },
            { LocKey.NamerGood, "Gut!" },
            { LocKey.NamerTasty, "Lecker!" },
            { LocKey.NamerGreat, "Super!" },
            { LocKey.NamerDelicious, "Köstlich!" },
            { LocKey.NamerAwesome, "Klasse!!" },
            { LocKey.NamerIncredible, "Unglaublich!!" },
            { LocKey.NamerExquisite, "Exquisit!!" },
            { LocKey.NamerGourmet, "Gourmet!!" },
            { LocKey.NamerJustBread, "Nur Brot..." },
            { LocKey.NamerDogtorBurger, "DOGTOR BURGER!!!" },
            { LocKey.TutMoveTitle, "BEWEG DICH!" },
            { LocKey.TutMoveTap, "Tippe LINKS oder RECHTS vom Dogtor, um ihn zu bewegen." },
            { LocKey.TutMoveSwipe, "Wische nach links oder rechts, um den Dogtor zu bewegen." },
            { LocKey.TutSwapTitle, "TAUSCHEN!" },
            { LocKey.TutSwapBody, "Tippe den Dogtor an, um die Stapel vor ihm zu tauschen!" },
            { LocKey.TutMatchTitle, "MATCH!" },
            { LocKey.TutMatchBody, "Zwei Gleiche platzen! Tausche zum passenden Stapel.\nPaare: {0}/{1}" },
            { LocKey.TutMatchDone, "Köstlich! Paare räumen die Theke und geben Punkte." },
            { LocKey.TutFastDropTitle, "EILIG?" },
            { LocKey.TutFastDropBody, "Tippe eine fallende Zutat an, damit sie schneller fällt!" },
            { LocKey.TutFastDropDone, "Zack! So bringst du ein Teil sofort nach unten." },
            { LocKey.TutBurgerTitle, "BURGER-ZEIT!" },
            { LocKey.TutBurgerBody, "TAUSCHE, damit alles auf dem unteren Brötchen landet! Deckel drauf." },
            { LocKey.TutBurgerDone, "Serviert! Größere Burger geben viel mehr Punkte." },
            { LocKey.TutOrderTitle, "SPEZIALBESTELLUNG!" },
            { LocKey.TutOrderBody, "Ein Gast will DIESEN! Reihenfolge egal - einfach bauen." },
            { LocKey.TutOrderDone, "Bestellungen erhöhen deinen Multiplikator auf JEDEN Punkt!" },
            { LocKey.TutPowerUpTitle, "POWER-UP!" },
            { LocKey.TutKetchupBody, "Gratis-Ketchup! Zieh ihn auf die volle Spalte." },
            { LocKey.TutKetchupDone, "Blitzblank! Ketchup leert eine ganze Spalte." },
            { LocKey.TutMustardBody, "Gratis-Senf! Wirf ihn auf eine Spalte: ihre zwei obersten Zutaten verschwinden überall!" },
            { LocKey.TutMustardDone, "Rundumschlag! Senf lohnt sich, wenn eine Zutat überall liegt." },
            { LocKey.TutSkewerBody, "Gratis-Spieß! Wirf ihn auf die Spalte mit dem vergrabenen Brötchen." },
            { LocKey.TutSkewerDone, "Gerettet und serviert! Ein vergrabenes Brötchen ist ein halber Burger." },
            { LocKey.TutReadyTitle, "BEREIT!" },
            { LocKey.TutReadyBody, "Tippe die Burger-Feen an für mehr Power-ups! Das Diner gehört dir." },
            { LocKey.TutTapToContinue, "ZUM WEITERMACHEN TIPPEN" },
            { LocKey.TutSkip, "SKIP" },
            { LocKey.ShopTitle, "SHOP" },
            { LocKey.ShopDogtorSkins, "DOGTOR-SKINS" },
            { LocKey.ShopIngredientSkins, "ZUTATEN-SKINS" },
            { LocKey.ShopProCookPack, "PROFI-KOCH-PAKET" },
            { LocKey.ShopStars, "STERNE" },
            { LocKey.ShopGems, "JUWELEN" },
            { LocKey.ShopRemoveAds, "WERBUNG ENTFERNEN" },
            { LocKey.ShopRewardAds, "BONUS-WERBUNG BLEIBT VERFÜGBAR" },
            { LocKey.ShopOneTimeBuy, "EINMAL-\nKAUF" },
            { LocKey.ShopThankYou, "DANKE FÜR DEINE\nUNTERSTÜTZUNG!" },
            { LocKey.ShopWatchAd, "WERBUNG ANSEHEN" },
            { LocKey.ShopTomorrow, "MORGEN!" },
            { LocKey.ShopLoading, "LÄDT..." },
            { LocKey.ShopRestorePurchases, "Käufe wiederherstellen" },
            { LocKey.ShopBuyAmount, "{0} kaufen" },
            { LocKey.ShopForCost, "für {0}" },
            { LocKey.ShopBuy, "KAUFEN" },
            { LocKey.ShopCancel, "ABBRECHEN" },
            { LocKey.ShopEquipped, "AKTIV" },
            { LocKey.ShopEquip, "ANLEGEN" },
            { LocKey.StatLevel, "Level" },
            { LocKey.StatScore, "Punkte" },
            { LocKey.SkinChefDefault, "Klassik-Koch" },
            { LocKey.SkinChefBurgerchain, "Fastfood-Koch" },
            { LocKey.SkinChefEuropean, "Europa-Koch" },
            { LocKey.SkinChefJapanese, "Japan-Koch" },
            { LocKey.SkinChefMexican, "Mexiko-Koch" },
            { LocKey.SkinChefRoyale, "Royale-Koch" },
            { LocKey.SkinBunDefault, "Klassik-Brötchen" },
            { LocKey.SkinBunGourmet, "Vollkornbrötchen" },
            { LocKey.SkinBunGold, "Goldbrötchen" },
            { LocKey.SkinBunRustic, "Landbrötchen" },
            { LocKey.SkinBunBlack, "Schwarzbrot" },
            { LocKey.SkinMeatDefault, "Klassik-Patty" },
            { LocKey.SkinMeatGourmet, "Chicken-Burger" },
            { LocKey.SkinMeatGold, "Gold-Patty" },
            { LocKey.SkinMeatVegan, "Vegan-Burger" },
            { LocKey.SkinMeatWagyu, "Wagyu-Steak" },
            { LocKey.SkinCheeseDefault, "Klassik-Käse" },
            { LocKey.SkinCheeseGourmet, "Cheddar" },
            { LocKey.SkinCheeseGold, "Goldkäse" },
            { LocKey.SkinCheeseShredded, "Reibekäse" },
            { LocKey.SkinCheeseBlue, "Blauschimmelkäse" },
            { LocKey.SkinTomatoDefault, "Klassik-Tomate" },
            { LocKey.SkinTomatoGourmet, "Kirschtomate" },
            { LocKey.SkinTomatoGold, "Goldtomate" },
            { LocKey.SkinTomatoPico, "Pico de Gallo" },
            { LocKey.SkinTomatoKumato, "Kumato" },
            { LocKey.SkinBaconDefault, "Bacon" },
            { LocKey.SkinBaconGourmet, "Speckwürfel" },
            { LocKey.SkinBaconGold, "Gold-Bacon" },
            { LocKey.SkinBaconPulledpork, "Pulled Pork" },
            { LocKey.SkinBaconIberic, "Iberico-Schinken" },
            { LocKey.SkinOnionDefault, "Klassik-Zwiebel" },
            { LocKey.SkinOnionGourmet, "Karamell-Zwiebel" },
            { LocKey.SkinOnionGold, "Goldzwiebel" },
            { LocKey.SkinOnionPickled, "Eingelegte Zwiebel" },
            { LocKey.SkinOnionCrispy, "Röstzwiebeln" },
            { LocKey.SkinPickleDefault, "Klassik-Gurke" },
            { LocKey.SkinPickleGourmet, "Gurkenrelish" },
            { LocKey.SkinPickleGold, "Goldgurke" },
            { LocKey.SkinPickleBellpepper, "Paprika" },
            { LocKey.SkinPickleJalapeno, "Jalapeño" },
            { LocKey.SkinLettuceDefault, "Klassik-Salat" },
            { LocKey.SkinLettuceGourmet, "Salatstreifen" },
            { LocKey.SkinLettuceGold, "Goldsalat" },
            { LocKey.SkinLettuceAvocado, "Avocado" },
            { LocKey.SkinLettucePurple, "Rotkohl" },
            { LocKey.SkinEggDefault, "Klassik-Ei" },
            { LocKey.SkinEggBoiled, "Gekochtes Ei" },
            { LocKey.SkinEggGold, "Gold-Ei" },
            { LocKey.SkinEggGourmet, "Wachtelei" },
            { LocKey.SkinEggOmelet, "Omelett" },
        };
    }
}
