using System.Collections.Generic;

namespace DogtorBurguer
{
    /// <summary>EN strings — one entry per LocKey (Loc's editor boot check screams on gaps).
    /// Machine-drafted 2026-09-08, native-phrasing polish pass the same day.</summary>
    public static class Strings_EN
    {
        public static readonly Dictionary<LocKey, string> Table = new()
        {
            { LocKey.SettingsTitle, "SETTINGS" },
            { LocKey.SettingsSoundOn, "Sound: ON" },
            { LocKey.SettingsSoundOff, "Sound: OFF" },
            { LocKey.SettingsControlsDrag, "Controls: Drag" },
            { LocKey.SettingsControlsTap, "Controls: Tap" },
            { LocKey.SettingsStartLevel, "START: LVL {0}" },
            { LocKey.SettingsQuit, "Quit to Menu" },
            { LocKey.SettingsLanguage, "Language: {0}" },
            { LocKey.MenuPlay, "PLAY" },
            { LocKey.MenuCredits, "CREDITS" },
            { LocKey.MenuShop, "SHOP" },
            { LocKey.MenuSupportDevs, "Support the devs!" },
            { LocKey.GameOverTitle, "GAME OVER..." },
            { LocKey.GameOverStarsEarned, "{0} stars earned!" },
            { LocKey.GameOverContinue, "Continue" },
            { LocKey.GameOverNoMoreContinues, "No more continues" },
            { LocKey.GameOverWatch, "Watch" },
            { LocKey.GameOverLoading, "Loading..." },
            { LocKey.GameOverMainMenu, "Main\nMenu" },
            { LocKey.GameOverRetry, "Retry" },
            { LocKey.HowToTitle, "HOW TO PLAY" },
            { LocKey.HowToPlayTutorial, "PLAY TUTORIAL" },
            { LocKey.HowToControls, "CONTROLS" },
            { LocKey.HowToControls1, "- Swipe left or right to move the chef." },
            { LocKey.HowToControls2, "- Tap the chef to rotate his plates." },
            { LocKey.HowToControls3, "- Tap a falling ingredient to drop it faster." },
            { LocKey.HowToControls4, "- Tap a preview arrow to spawn it right away." },
            { LocKey.HowToMatching, "MATCHING" },
            { LocKey.HowToMatching1, "- Two stacked ingredients of the same type pop and score points." },
            { LocKey.HowToMatching2, "- Keep the columns low: if one overflows, the run ends!" },
            { LocKey.HowToBurgers, "BURGERS" },
            { LocKey.HowToBurgers1, "- Open with a bottom bun." },
            { LocKey.HowToBurgers2, "- Stack any ingredients on top." },
            { LocKey.HowToBurgers3, "- Close with a top bun to serve the burger." },
            { LocKey.HowToBurgers4, "- Bigger burgers score more!" },
            { LocKey.HowToOrders, "SPECIAL ORDERS" },
            { LocKey.HowToOrders1, "- Serve a burger that fits the shown order." },
            { LocKey.HowToOrders2, "- Orders pay stars and raise your multiplier." },
            { LocKey.PowerUps, "POWER-UPS" },
            { LocKey.HowToPowerUpsA1, "- The Burger Fairy brings gems, stars and power-ups. Tap her before she leaves!" },
            { LocKey.HowToPowerUpsA2, "- Drag a power-up from its slot onto a column to use it." },
            { LocKey.HowToPowerUpsB1, "- Ketchup clears its column." },
            { LocKey.HowToPowerUpsB2, "- Mustard sweeps the top two ingredient types of its column from the whole board." },
            { LocKey.HowToPowerUpsB3, "- Skewer pushes a bottom bun down to the base of its column." },
            { LocKey.CreditsTitle, "CREDITS" },
            { LocKey.CreditsGameBy, "A GAME BY" },
            { LocKey.CreditsArtBy, "ART BY" },
            { LocKey.CreditsMusicBy, "MUSIC BY" },
            { LocKey.SpecialOrder, "SPECIAL ORDER" },
            { LocKey.TooBad, "Too bad!" },
            { LocKey.OrderComplete, "Order Complete!" },
            { LocKey.NamerGood, "Good!" },
            { LocKey.NamerTasty, "Tasty!" },
            { LocKey.NamerGreat, "Great!" },
            { LocKey.NamerDelicious, "Delicious!" },
            { LocKey.NamerAwesome, "Awesome!!" },
            { LocKey.NamerIncredible, "Incredible!!" },
            { LocKey.NamerExquisite, "Exquisite!!" },
            { LocKey.NamerGourmet, "Gourmet!!" },
            { LocKey.NamerJustBread, "Just Bread..." },
            { LocKey.NamerDogtorBurger, "DOGTOR BURGER!!!" },
            { LocKey.TutMoveTitle, "MOVE!" },
            { LocKey.TutMoveTap, "Tap LEFT or RIGHT of the Dogtor to move him between the counters." },
            { LocKey.TutMoveSwipe, "Swipe left or right to move the Dogtor between the counters." },
            { LocKey.TutSwapTitle, "SWAP!" },
            { LocKey.TutSwapBody, "Tap the Dogtor to swap the two stacks in front of him!" },
            { LocKey.TutMatchTitle, "MATCH!" },
            { LocKey.TutMatchBody, "Two of a kind pop! Swap the stacks so the falling patty lands on its twin." },
            { LocKey.TutMatchDone, "Delicious! Matching clears the counter and scores points." },
            { LocKey.TutBurgerTitle, "BURGER TIME!" },
            { LocKey.TutBurgerBody, "Your turn! A bottom bun opens the burger - SWAP the stacks so every falling piece lands ON it. Close it with the top bun!" },
            { LocKey.TutBurgerDone, "Served! Bigger burgers score much more." },
            { LocKey.TutOrderTitle, "SPECIAL ORDER!" },
            { LocKey.TutOrderBody, "A customer wants THIS exact burger! Ingredient ORDER does not matter - build it and serve it!" },
            { LocKey.TutOrderDone, "Orders fill the gauge and raise your score multiplier - for EVERY point you earn!" },
            { LocKey.TutPowerUpTitle, "POWER-UP!" },
            { LocKey.TutPowerUpBody, "A free Ketchup! Drag it from its slot onto the messy column to clean it." },
            { LocKey.TutPowerUpDone, "Spotless! Burger Fairies bring more power-ups - tap them when they fly by." },
            { LocKey.TutReadyTitle, "READY!" },
            { LocKey.TutReadyBody, "The diner is yours. Serve them well, Dogtor!" },
            { LocKey.TutTapToContinue, "TAP TO CONTINUE" },
            { LocKey.TutSkip, "SKIP" },
            { LocKey.ShopTitle, "SHOP" },
            { LocKey.ShopDogtorSkins, "DOGTOR SKINS" },
            { LocKey.ShopIngredientSkins, "INGREDIENT SKINS" },
            { LocKey.ShopProCookPack, "PRO COOK PACK" },
            { LocKey.ShopStars, "STARS" },
            { LocKey.ShopGems, "GEMS" },
            { LocKey.ShopRemoveAds, "REMOVE ADS" },
            { LocKey.ShopRewardAds, "REWARD ADS STILL AVAILABLE" },
            { LocKey.ShopOneTimeBuy, "ONE\nTIME\nBUY" },
            { LocKey.ShopThankYou, "THANK YOU FOR\nSUPPORTING US!" },
            { LocKey.ShopWatchAd, "WATCH AD" },
            { LocKey.ShopTomorrow, "TOMORROW!" },
            { LocKey.ShopLoading, "LOADING..." },
            { LocKey.ShopRestorePurchases, "Restore Purchases" },
            { LocKey.ShopBuyAmount, "Buy {0}" },
            { LocKey.ShopForCost, "for {0}" },
            { LocKey.ShopBuy, "BUY" },
            { LocKey.ShopCancel, "CANCEL" },
            { LocKey.ShopEquipped, "EQUIPPED" },
            { LocKey.ShopEquip, "EQUIP" },
            { LocKey.StatLevel, "Level" },
            { LocKey.StatScore, "Score" },
        };
    }
}
