using System.Collections.Generic;

namespace DogtorBurguer
{
    /// <summary>IT strings — one entry per LocKey (Loc's editor boot check screams on gaps).
    /// Machine-drafted 2026-09-08, native-phrasing polish pass the same day.</summary>
    public static class Strings_IT
    {
        public static readonly Dictionary<LocKey, string> Table = new()
        {
            { LocKey.SettingsTitle, "IMPOSTAZIONI" },
            { LocKey.SettingsSoundOn, "Effetti: SÌ" },
            { LocKey.SettingsSoundOff, "Effetti: NO" },
            { LocKey.SettingsMusicOn, "Musica: SÌ" },
            { LocKey.SettingsMusicOff, "Musica: NO" },
            { LocKey.SettingsControlsDrag, "Controlli: Trascina" },
            { LocKey.SettingsControlsTap, "Controlli: Tocca" },
            { LocKey.SettingsStartLevel, "INIZIO: LIVELLO {0}" },
            { LocKey.SettingsQuit, "Torna al Menu" },
            { LocKey.SettingsLanguage, "Lingua: {0}" },
            { LocKey.SettingsRestart, "Ricomincia" },
            { LocKey.MenuPlay, "GIOCA" },
            { LocKey.MenuResume, "RIPRENDI" },
            { LocKey.MenuCredits, "CREDITI" },
            { LocKey.MenuShop, "NEGOZIO" },
            { LocKey.MenuSupportDevs, "Sostieni i dev!" },
            { LocKey.GameOverTitle, "GAME OVER..." },
            { LocKey.GameOverStarsEarned, "Hai guadagnato {0} stelle!" },
            { LocKey.GameOverContinue, "Continua" },
            { LocKey.GameOverNoMoreContinues, "Non puoi più continuare" },
            { LocKey.GameOverWatch, "Guarda" },
            { LocKey.GameOverLoading, "Caricamento..." },
            { LocKey.GameOverMainMenu, "Menu\nPrincipale" },
            { LocKey.GameOverRetry, "Riprova" },
            { LocKey.HowToTitle, "COME SI GIOCA" },
            { LocKey.HowToPlayTutorial, "GIOCA TUTORIAL" },
            { LocKey.HowToControls, "CONTROLLI" },
            { LocKey.HowToControls1, "Scorri, o tocca a sinistra o destra dello chef, per spostarlo." },
            { LocKey.HowToControls2, "Tocca lo chef per scambiare le due colonne davanti a lui." },
            { LocKey.HowToControls3, "Tocca un ingrediente in caduta per accelerarlo." },
            { LocKey.HowToControls4, "Tocca un ingrediente in alto per farlo scendere subito." },
            { LocKey.HowToMatching, "COPPIE" },
            { LocKey.HowToMatching1, "Due ingredienti uguali impilati scoppiano e danno punti." },
            { LocKey.HowToMatching2, "Tieni basse le colonne: se una trabocca, è finita!" },
            { LocKey.HowToBurgers, "BURGER" },
            { LocKey.HowToBurgers1, "Apri con il pane di sotto." },
            { LocKey.HowToBurgers2, "Impila ingredienti sopra." },
            { LocKey.HowToBurgers3, "Chiudi con il pane di sopra per servire il burger." },
            { LocKey.HowToBurgers4, "I burger più grandi valgono di più!" },
            { LocKey.HowToOrders, "ORDINI SPECIALI" },
            { LocKey.HowToOrders1, "Servi un burger che corrisponda all'ordine mostrato." },
            { LocKey.HowToOrders2, "Gli ordini fanno guadagnare stelle e alzano il moltiplicatore." },
            { LocKey.PowerUps, "POWER-UP" },
            { LocKey.HowToPowerUpsA1, "La Fata Burger porta gemme, stelle e power-up. Toccala prima che vada via!" },
            { LocKey.HowToPowerUpsA2, "Trascina un power-up dal suo slot su una colonna per usarlo." },
            { LocKey.HowToPowerUpsB1, "Il ketchup svuota la sua colonna." },
            { LocKey.HowToPowerUpsB2, "La senape prende i due tipi in cima alla sua colonna e li spazza via da tutto il tabellone." },
            { LocKey.HowToPowerUpsB3, "Lo spiedino spinge il pane di sotto fino alla base della colonna." },
            { LocKey.CreditsTitle, "CREDITI" },
            { LocKey.CreditsGameBy, "UN GIOCO DI" },
            { LocKey.CreditsArtBy, "ARTE DI" },
            { LocKey.CreditsMusicBy, "MUSICA DI" },
            { LocKey.SpecialOrder, "ORDINE SPECIALE" },
            { LocKey.MultTab, "MULT" },
            { LocKey.TooBad, "Peccato!" },
            { LocKey.OrderComplete, "Ordine completato!" },
            { LocKey.NamerGood, "Buono!" },
            { LocKey.NamerTasty, "Gustoso!" },
            { LocKey.NamerGreat, "Ottimo!" },
            { LocKey.NamerDelicious, "Delizioso!" },
            { LocKey.NamerAwesome, "Fantastico!!" },
            { LocKey.NamerIncredible, "Incredibile!!" },
            { LocKey.NamerExquisite, "Squisito!!" },
            { LocKey.NamerGourmet, "Gourmet!!" },
            { LocKey.NamerJustBread, "Solo pane..." },
            { LocKey.NamerDogtorBurger, "DOGTOR BURGER!!!" },
            { LocKey.TutMoveTitle, "MUOVITI!" },
            { LocKey.TutMoveTap, "Tocca a SINISTRA o a DESTRA del Dogtor per spostarlo." },
            { LocKey.TutMoveSwipe, "Scorri a sinistra o destra per spostare il Dogtor." },
            { LocKey.TutSwapTitle, "SCAMBIA!" },
            { LocKey.TutSwapBody, "Tocca il Dogtor per scambiare le colonne davanti a lui!" },
            { LocKey.TutMatchTitle, "COPPIA!" },
            { LocKey.TutMatchBody, "Due uguali scoppiano! Scambia per farlo cadere sull'uguale.\nCoppie: {0}/{1}" },
            { LocKey.TutMatchDone, "Delizioso! Le coppie puliscono il bancone e danno punti." },
            { LocKey.TutFastDropTitle, "DI FRETTA?" },
            { LocKey.TutFastDropBody, "Tocca un ingrediente che cade per farlo scendere veloce!" },
            { LocKey.TutFastDropDone, "Zac! Fai arrivare giù un pezzo quando ti serve." },
            { LocKey.TutBurgerTitle, "BURGER TIME!" },
            { LocKey.TutBurgerBody, "SCAMBIA per farli cadere sul panino di sotto! Chiudi col sopra." },
            { LocKey.TutBurgerDone, "Servito! I burger più grandi valgono molto di più." },
            { LocKey.TutOrderTitle, "ORDINE SPECIALE!" },
            { LocKey.TutOrderBody, "Un cliente vuole QUESTO! L'ordine non conta: costruiscilo." },
            { LocKey.TutOrderDone, "Gli ordini alzano il moltiplicatore su OGNI punto!" },
            { LocKey.TutPowerUpTitle, "POWER-UP!" },
            { LocKey.TutKetchupBody, "Ketchup gratis! Trascinalo sulla colonna piena." },
            { LocKey.TutKetchupDone, "Impeccabile! Il ketchup svuota un'intera colonna." },
            { LocKey.TutMustardBody, "Senape gratis! Lasciala su una colonna: i suoi due ingredienti in cima spariscono ovunque!" },
            { LocKey.TutMustardDone, "Che sventagliata! La senape rende se un ingrediente è ovunque." },
            { LocKey.TutSkewerBody, "Spiedino gratis! Lascialo sulla colonna col panino sepolto." },
            { LocKey.TutSkewerDone, "Salvato e servito! Un panino sepolto è un burger in attesa." },
            { LocKey.TutReadyTitle, "PRONTO!" },
            { LocKey.TutReadyBody, "Tocca le Fate Burger per altri power-up! Il locale è tuo." },
            { LocKey.TutTapToContinue, "TOCCA PER CONTINUARE" },
            { LocKey.TutSkip, "SALTA" },
            { LocKey.ShopTitle, "NEGOZIO" },
            { LocKey.ShopDogtorSkins, "SKIN DOGTOR" },
            { LocKey.ShopIngredientSkins, "SKIN INGREDIENTI" },
            { LocKey.ShopProCookPack, "PACCHETTO PRO CHEF" },
            { LocKey.ShopStars, "STELLE" },
            { LocKey.ShopGems, "GEMME" },
            { LocKey.ShopRemoveAds, "RIMUOVI PUBBLICITÀ" },
            { LocKey.ShopRewardAds, "GLI ANNUNCI PREMIO RESTANO" },
            { LocKey.ShopOneTimeBuy, "ACQUISTO\nUNICO" },
            { LocKey.ShopThankYou, "GRAZIE PER IL\nTUO SOSTEGNO!" },
            { LocKey.ShopWatchAd, "GUARDA VIDEO" },
            { LocKey.ShopTomorrow, "DOMANI!" },
            { LocKey.ShopLoading, "CARICAMENTO..." },
            { LocKey.ShopRestorePurchases, "Ripristina acquisti" },
            { LocKey.ShopBuyAmount, "Compra {0}" },
            { LocKey.ShopForCost, "per {0}" },
            { LocKey.ShopBuy, "COMPRA" },
            { LocKey.ShopCancel, "ANNULLA" },
            { LocKey.ShopEquipped, "IN USO" },
            { LocKey.ShopEquip, "USA" },
            { LocKey.StatLevel, "Livello" },
            { LocKey.StatScore, "Punti" },
            { LocKey.SkinChefDefault, "Chef classico" },
            { LocKey.SkinChefBurgerchain, "Chef fast food" },
            { LocKey.SkinChefEuropean, "Chef europeo" },
            { LocKey.SkinChefJapanese, "Chef giapponese" },
            { LocKey.SkinChefMexican, "Chef messicano" },
            { LocKey.SkinChefRoyale, "Chef Royale" },
            { LocKey.SkinBunDefault, "Pane classico" },
            { LocKey.SkinBunGourmet, "Pane integrale" },
            { LocKey.SkinBunGold, "Pane d'oro" },
            { LocKey.SkinBunRustic, "Pane rustico" },
            { LocKey.SkinBunBlack, "Pane nero" },
            { LocKey.SkinMeatDefault, "Carne classica" },
            { LocKey.SkinMeatGourmet, "Burger di pollo" },
            { LocKey.SkinMeatGold, "Carne d'oro" },
            { LocKey.SkinMeatVegan, "Burger vegano" },
            { LocKey.SkinMeatWagyu, "Bistecca wagyu" },
            { LocKey.SkinCheeseDefault, "Formaggio classico" },
            { LocKey.SkinCheeseGourmet, "Cheddar" },
            { LocKey.SkinCheeseGold, "Formaggio d'oro" },
            { LocKey.SkinCheeseShredded, "Formaggio grattugiato" },
            { LocKey.SkinCheeseBlue, "Erborinato" },
            { LocKey.SkinTomatoDefault, "Pomodoro classico" },
            { LocKey.SkinTomatoGourmet, "Pomodorino" },
            { LocKey.SkinTomatoGold, "Pomodoro d'oro" },
            { LocKey.SkinTomatoPico, "Pico de gallo" },
            { LocKey.SkinTomatoKumato, "Kumato" },
            { LocKey.SkinBaconDefault, "Pancetta" },
            { LocKey.SkinBaconGourmet, "Pancetta a cubetti" },
            { LocKey.SkinBaconGold, "Pancetta d'oro" },
            { LocKey.SkinBaconPulledpork, "Maiale sfilacciato" },
            { LocKey.SkinBaconIberic, "Prosciutto iberico" },
            { LocKey.SkinOnionDefault, "Cipolla classica" },
            { LocKey.SkinOnionGourmet, "Cipolla caramellata" },
            { LocKey.SkinOnionGold, "Cipolla d'oro" },
            { LocKey.SkinOnionPickled, "Cipolla sottaceto" },
            { LocKey.SkinOnionCrispy, "Cipolla croccante" },
            { LocKey.SkinPickleDefault, "Cetriolino classico" },
            { LocKey.SkinPickleGourmet, "Relish di cetrioli" },
            { LocKey.SkinPickleGold, "Cetriolino d'oro" },
            { LocKey.SkinPickleBellpepper, "Peperone" },
            { LocKey.SkinPickleJalapeno, "Jalapeño" },
            { LocKey.SkinLettuceDefault, "Lattuga classica" },
            { LocKey.SkinLettuceGourmet, "Lattuga tagliata" },
            { LocKey.SkinLettuceGold, "Lattuga d'oro" },
            { LocKey.SkinLettuceAvocado, "Avocado" },
            { LocKey.SkinLettucePurple, "Cavolo viola" },
            { LocKey.SkinEggDefault, "Uovo classico" },
            { LocKey.SkinEggBoiled, "Uovo sodo" },
            { LocKey.SkinEggGold, "Uovo d'oro" },
            { LocKey.SkinEggGourmet, "Uovo di quaglia" },
            { LocKey.SkinEggOmelet, "Frittata" },
        };
    }
}
